### ISSUE TITLE
Improve Workspace Management & Releasing

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1008]
## Problem

When the repo was converted to a monorepo, the following tools were selected/tried out:

- npm workspace: because npm was already used
- lerna: inspired from https://github.com/libp2p/js-libp2p-interfaces/
- semantic-release: inspired from https://github.com/libp2p/js-libp2p-interfaces/

A number of issues have been encountered:

1. With npm, if a dependency is installed for one package, it's available for all packages, meaning we can run into issue where a dependency declaration is missing: #1006 (note: a similar behaviour was noticed with yarn workspace on js-waku examples in the past)
2. `Lerna run build` fails the first time on a clean local repo but not in CI. Error reporting is unhelpful
3. Lerna takes several seconds to kick off
4. `semantic-release` does not work with workspaces, `multi-semantic-release` and `semantic-release-monorepo` were tried out with no success
5. Lerna's [tooted](https://lerna.js.org/docs/getting-started#visualizing-workspace) dependency graph feature does not work (error with Nx daemon).

### workspaces

A way to easily build, check & test all repos with one command. Performance needs to be adequate.
The tool should read the dependency graph to know in which order should the repos be built.

### Releasing

Superseded by https://github.com/waku-org/js-waku/issues/890

Releasing should be easy which means:

- At release time, the tool should know what packages need to be released
- At release time, the tool should know how versions should be bumped
- A changelog should be maintained.

There are several way to solve this:
- semantic release: Commit/PR title dictate the release version bump, what packages to be released is deduced from files changes by commits
- changesets: Developers add a changeset when doing a change, at release, changesets are used to generate changelog, bump versions and release packages.

`semantic-release` package seems to be a [no go for monorepo](https://dev.to/antongolub/the-chronicles-of-semantic-release-and-monorepos-5cfc),

Releasing with version bumping and changelog update (if not done at commit time) does not need to happen in the CI.

#### Pre-releasing

A different feature that was present in js-waku was that every PR was published. Enabling easy integration in examples before a release.

Having a tool that does the same but only release the packages changed in the PR would be useful.

### Other

Knowing that (1) was also an issue with yarn workspaces last year, it seems to be a difficult issue. Maybe a separate tool is needed to fix this.

I don't have a great experience with `yarn` due to its odd version handling but `yarn workspaces` might be the best way to go. Would be good to try `npm` first.

## Proposed Solutions

- Try `npm workspaces` without lerna
- Try `npm workspaces` with a tool different from lerna
- Try `changesets`
- Try `yarn workspaces`

**Comment by fryorcraken** [comment]
IMHO `npm workspaces` is fine for now. The priority should be in sorting releasing.

**Comment by weboko** [comment]
I think this one can be closed as the very last point of this issue `Pre-releasing` is tracked in https://github.com/waku-org/js-waku/issues/1543 and others are done.
