### ISSUE TITLE
Default Libp2p Agent Version to `js-waku` and make it easily overridable

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1009]
This is a **feature request**

## Problem

Described in https://github.com/waku-org/pm/issues/3

## Acceptance Criteria

- [ ] libp2p agent version is `js-waku` by default
- [ ] An API is available to override the agent version

**Comment by alrevuelta** [comment]
https://github.com/waku-org/js-waku/pull/1016 closed this right?
Thanks @danisharora099 for the PR!! 👏
