### ISSUE TITLE
Tests failing after upgrading nwaku from v0.11 to v0.12

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1015]
This is a **bug report**

## Problem

After the upgrade of `nwaku` on `js-waku` from `v0.11` to `v0.12`, the tests are now failing.

Logs: https://pastebin.com/dxxTJfzR

## Debugging
logged the messages received from `queryGenerator` on the `Generator` test and it misses `Message 9` which makes it fail:
```Message 10
Message 11
Message 12
Message 13
Message 14
Message 15
Message 16
Message 17
Message 18
Message 19
Message 0
Message 1
Message 2
Message 3
Message 4
Message 5
Message 6
Message 7
Message 8
```

**Comment by fryorcraken** [comment]
It looks like a nwaku issue from my investigation: https://github.com/status-im/nwaku/issues/1371

**Comment by danisharora099** [comment]
Has been resolved implicitly with https://github.com/status-im/nwaku/issues/1371
