### ISSUE TITLE
feat request: add tests for dns-discovery

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1086]
This is a support request

## Problem

The current test written for `dns-discovery` doesn't actually run as a part of the `test` script, which upon running (indirectly) doesn't successfully pass for me.

## Notes

- upon running `mocha` on the file directly, it fails with some compilation red herrings: ```[mocha Error: No test files found: "test/" npm ERR! Test failed](https://stackoverflow.com/questions/54805319/mocha-error-no-test-files-found-test-npm-err-test-failed)```
- Upon porting a part of the test into `packages/tests`, and running the test, it doesn't work as expected: https://github.com/waku-org/nwaku/issues/1464

**Comment by fryorcraken** [comment]
How did you run mocha?

**Comment by fryorcraken** [comment]
> As dns-discovery's package.json misses the test* script, directly by running npx mocha to test things.

Well, that's your issue. You need to set an env var to run mocha (see other `package.json` files).

**Comment by weboko** [comment]
I just played a bit with it but does this PR resolves your issue, @danisharora099 ?
https://github.com/waku-org/js-waku/pull/1154
