### ISSUE TITLE
bug: unable to dial to peers received from peer-exchange query

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1113]
This is a bug report

## Problem

When a PeerId, received as a response from a peer exchange request, the dial fails with an error: `Error: The dial request has no valid addresses` 

## Proposed solution
ref: https://github.com/ipfs/js-ipfs/issues/4185

## Notes

To repro: https://github.com/waku-org/js-waku/pull/1116

- js-waku version: latest master (https://github.com/waku-org/js-waku/commit/0b083201c6f585ad1b3267c1571df5f1b81a1355)
- Environment: node18
- Nodes connected to: Wakuv2 test fleet
- Debugging logs:
```  Peer Exchange
  waku:waku Waku node created 12D3KooWGC4JLHT9LQRmTKx5ibLAvFNCUTwiFFzgzm4gZCBvXNZg relay: false, store: true, light push: true, filter: true, peer exchange: true  +0ms
  waku:waku Found peer 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, dialing. +1s
Found peer 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, dialing.
  waku:waku Found peer 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, dialing. +4ms
Found peer 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, dialing.
{ tags1: [] }
  waku:wait-for-remote-peer Resolving for /vac/waku/peer-exchange/2.0.0-alpha1 [
  '/ipfs/id/1.0.0',
  '/ipfs/ping/1.0.0',
  '/libp2p/autonat/1.0.0',
  '/libp2p/circuit/relay/0.2.0/hop',
  '/vac/waku/filter/2.0.0-beta1',
  '/vac/waku/lightpush/2.0.0-beta1',
  '/vac/waku/peer-exchange/2.0.0-alpha1',
  '/vac/waku/relay/2.0.0',
  '/vac/waku/store/2.0.0-beta4',
  '/vac/waku/swap/2.0.0-beta1'
] +0ms
  waku:libp2p-utils Using codec /vac/waku/peer-exchange/2.0.0-alpha1 +0ms
Secp256k1PeerIdImpl [PeerId(16Uiu2HAmTtLizeHTk59VDjPWttD39AHfu4RhpyyoiGf76YHqMwXK)] {
  type: 'secp256k1',
  multihash: Digest {
    code: 0,
    size: 37,
    digest: <Buffer 08 02 12 21 03 e2 4a e4 41 0e 97 1d 45 16 ab 9e 85 7b 21 22 26 14 ac a2 a3 55 a9 69 8c 54 9f a3 46 5c dd 60 d6>,
    bytes: Uint8Array(39) [
        0,  37,   8,   2, 18,  33,   3, 226,  74,
      228,  65,  14, 151, 29,  69,  22, 171, 158,
      133, 123,  33,  34, 38,  20, 172, 162, 163,
       85, 169, 105, 140, 84, 159, 163,  70,  92,
      221,  96, 214
    ]
  },
  privateKey: undefined,
  publicKey: <Buffer 08 02 12 21 03 e2 4a e4 41 0e 97 1d 45 16 ab 9e 85 7b 21 22 26 14 ac a2 a3 55 a9 69 8c 54 9f a3 46 5c dd 60 d6>
} Error: The dial request has no valid addresses
    at DefaultDialer.dial (file:///Users/danisharora099/Developer/status/waku/node_modules/libp2p/src/connection-manager/dialer/index.ts:190:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EventTarget.openConnection (file:///Users/danisharora099/Developer/status/waku/node_modules/libp2p/src/connection-manager/index.ts:569:26)
    at async EventTarget.dial (file:///Users/danisharora099/Developer/status/waku/node_modules/libp2p/src/libp2p.ts:354:12)
    at async WakuPeerExchange.callback (file:///Users/danisharora099/Developer/status/waku/packages/tests/tests/peer_exchange.node.spec.ts:76:11)
    at async file:///Users/danisharora099/Developer/status/waku/packages/peer-exchange/src/waku_peer_exchange.ts:105:9 {
  code: 'ERR_NO_VALID_ADDRESSES'
}
Secp256k1PeerIdImpl [PeerId(16Uiu2HAmDJdYGZd9tztuuLLwLi7uXnC8SX278X5YAibejFSde2rw)] {
  type: 'secp256k1',
```

**Comment by fryorcraken** [comment]
How are we trying to dial the peers received from peer-exchange query? I am guessing we are not processing the ws multiaddr correctly.

1. First, check that the mutliaddr for the record is present in the received ENR (I believe this was an issue in some instances)
2. Ensure that the mutliaddr is then processed. Most likely, it needs to be saved in the libp2p peer store. or emitted in the `PeerInfo` object by the peer discovery PeerExchange class. And then the connection manager needs to process the multiaddr in the `PeerInfo` object which has been emitted and use it to dial.

**Comment by fryorcraken** [comment]
Here: https://github.com/waku-org/js-waku/blob/0b083201c6f585ad1b3267c1571df5f1b81a1355/packages/core/src/lib/waku.ts#L140

On the peer id is used to dial

Here, the peer is tagged in the `peerStore` but the multiaddr is never recorded: https://github.com/waku-org/js-waku/blob/0b083201c6f585ad1b3267c1571df5f1b81a1355/packages/peer-exchange/src/waku_peer_exchange_discovery.ts#L92

I must say I don't understand why it works with bootstrap but not with peer exchange:

https://github.com/libp2p/js-libp2p-bootstrap/blob/dffd518cdb5924686b326b3f78a7823597715119/src/index.ts#L136

**Comment by fryorcraken** [comment]
I am not sure if https://github.com/ipfs/js-ipfs/issues/4185 is relevant. Log the multiaddr to verify they are `wss` as expected.

**Comment by danisharora099** [comment]
The logged multiaddrs is `wss`:
```  <Multiaddr 36326e6f64652d30312e67632d75732d63656e7472616c312d612e676f2d77616b752e70726f642e737461747573696d2e6e65740601bbde03 - /dns4/node-01.gc-us-central1-a.go-waku.prod.statusim.net/tcp/443/wss>```

**Comment by danisharora099** [comment]
This might help with reproducing: https://github.com/waku-org/js-waku/pull/1116

**Comment by danisharora099** [comment]
This issue was resolved with a bug during multiaddress parsing.
