### ISSUE TITLE
@waku/dns-discovery missing exported types

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1124]
This is a **bug report**

## Problem

`@waku/dns-discovery` seems to not be exporting its types correctly // `@waku/dns-discovery` when imported gives an error: `Could not find a declaration file for module '@waku/dns-discovery'.`

## Proposed Solutions

To be investigated

**Comment by danisharora099** [comment]
Updated issue: https://github.com/waku-org/js-waku-examples/issues/191

**Comment by fryorcraken** [comment]
Still valid?

**Comment by weboko** [comment]
I checked and issue is still present. I have a fix but I want to check other packages since it might be present there too.

**Comment by weboko** [comment]
Issue is complete with the #1359 
Removal of the type declaration should be done in https://github.com/waku-org/js-waku-examples/issues/191
