### ISSUE TITLE
chore: check dev dependencies

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1126]
This is a **support request**

## Problem
Some of the dependencies were moved from `devDependencies` to `dependencies` after new linter rule was introduced. 
https://github.com/waku-org/js-waku/pull/1111
https://github.com/waku-org/js-waku/pull/1111/files#r1080568044

## Proposed Solutions
Need organise them properly.

**Comment by fryorcraken** [comment]
Note that more urgently,  the dependency @waku/peer-exchange > @libp2p/interface-peer-discovery-compliance-tests should be removed as it impose a usage of NodeJS 18 that creates an error at installation.

```
▶ nvm use 16
Now using node v16.17.0 (npm v8.19.3)

▶ npm i @waku/core
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@20.0.2',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.17.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 1625 packages, and audited 1836 packages in 3m

324 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

**Comment by fryorcraken** [comment]
> This one `@libp2p/interface-peer-discovery-compliance-tests` is definitely not used at all so I removed it. As for the logs that you shared - I don't see any error, it seems as just a warning so everything should work. I was not able to see any errors in node versions 16 - 19.
> 
> Can you clarify what you meant, @fryorcraken?

Removing the dep quoted should be good enough to remove the warn :+1:
