### ISSUE TITLE
Relay interface doesn't include 'observers'

### ISSUE THREAD

**Issue by therealjmj** [waku-org/js-waku#1142]
This is a **feature or change request**

## Problem

waku.relay (IRelay) does not provide public accessor for `observers`.

## Proposed Solutions

Make `observers` Map publicly accessible on IRelay interface.

## Notes

Current workaround: 

```
// @ts-ignore - private accessor
return waku.relay.observers.keys() as string[];
```

**Comment by fryorcraken** [comment]
@therealjmj can you elaborate a bit more on why this is needed? the `observers` Map is an implementation details on how observers are tracked in relay. I'd prefer to provide the API you need (e.g. `unsusbcribeAll`) as it would be more future proof.

**Comment by therealjmj** [comment]
unsubscribeAll would be a decent implementation that could also help.
For our use case, we print out the active observers for logging.
This helped us catch one major bug.

**Comment by fryorcraken** [comment]
Ok, logging requirements is a good enough reason to add to interface IMO

**Comment by weboko** [comment]
@therealjmj can you, please, elaborate on what kind of bug that was and how exactly additional logging helped you?

**Comment by therealjmj** [comment]
Our implementation swaps out the observers mid-session, whenever a user changes their blockchain network.

The bug occurred because the observers were not properly removed, so they stacked, resulting in a ton of observers and poor bandwidth/performance.

Logging for observers, when they're changed, helped us discover and patch the issue.

See this implementation for more details:
https://github.com/Railgun-Community/waku-relayer-client/blob/main/src/waku/waku-observers.ts#L37

**Comment by weboko** [comment]
@therealjmj thank you for sharing! 

I still think we can cover this need without making `observers` public.
I think we should not expose it as it is an internal representation that might be changed in the future.

What I think we can do is to make some sort of API to subscribe to changes of the observers store. 
It will add friction and we will need to make sure it is reliable but it will help us not leak internal representation. 

@fryorcraken, @danisharora099  what do you think?

**Comment by fryorcraken** [comment]
> @therealjmj thank you for sharing!
> 
> I still think we can cover this need without making `observers` public. I think we should not expose it as it is an internal representation that might be changed in the future.
> 
> What I think we can do is to make some sort of API to subscribe to changes of the observers store. It will add friction and we will need to make sure it is reliable but it will help us not leak internal representation.
> 
> @fryorcraken, @danisharora099 what do you think?

Sounds good. I guess best way to move forward is having a PR and see if it satisfies @therealjmj 's needs

**Comment by therealjmj** [comment]
Any route for logging is ok with me - thanks friends!

**Comment by weboko** [comment]
Here is draft PR for the idea I am proposing https://github.com/waku-org/js-waku/pull/1213

cc @danisharora099 @fryorcraken @therealjmj

**Comment by fryorcraken** [comment]
Solution does not satisfy initial requirements.

**Comment by weboko** [comment]
I think it will be safe to close with https://github.com/waku-org/js-waku/pull/1249 once @therealjmj gives feedback

**Comment by fryorcraken** [comment]
Done with #1249
