### ISSUE TITLE
Investigate how msgIdProvider are generated in Waku Relay

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1179]
This is a **investigation request**

## Problem

See https://github.com/waku-org/nwaku/pull/1556

## Proposed Solutions

Understand what is done in js-waku and ensure it's aligned with go-waku and nwaku.

## Notes

The behaviour is most likely inherited from `@ChainSafe/libp2p-gossipsub` and it's unclear whether we can override it.

**Comment by weboko** [comment]
`msgId` configuration is defined [here](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/f62859b346474ff3e29d59e31449b15d60e054d6/src/index.ts#L445) and can be influenced by `msgIdFn` options passed to `PubSub` class.

If not passed depending on `Sign` policy it will use one of pre-defined implementations. In our case for `StrictNoSign` it will be [this one](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/f62859b346474ff3e29d59e31449b15d60e054d6/src/utils/msgIdFn.ts#L22) which is essentially `sha256`.

For `nwaku` we use `sha256` as defined [here](https://github.com/waku-org/nwaku/blob/3e14686950f9073f97202319717c52fbe115091b/waku/v2/waku_relay/message_id.nim#L32) and the [same](https://github.com/waku-org/go-waku/blob/88ecf728a3b8e9abdd130f244453263a7f94fc95/waku/v2/protocol/relay/waku_relay.go#L59) goes for `go-waku`

Hereby I declare implementations are on the same page. 📜
