### ISSUE TITLE
feat: simplify sending/receiving API

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1220]
This is a **bug report/feature or change request/support request**

## Problem

From discussion https://github.com/waku-org/waku-ui/pull/1#discussion_r1109154479

> we can have the Light node and relay node implement an interface like that
```ts
interface WakuNode {
   sender: Sender;
   receiver: Receiver
}
```

## Proposed Solutions

- [x] Create `ISender` and `IReceiver` interfaces
- [x] relay, filter, light push to implement these interfaces
- [x] take the opportunity to align API for these protocols
- [x] enables Waku node to also implement the interfaces and use lightpush+filter or relay under the hood (user only need to choose what protocol to use at node creation)

## Notes

Other improvement:

Make `filter.subscribe` and probably `relay.addObserver` too accept a single decoder OR an array of decoder.

**Comment by weboko** [comment]
I believe it is done by https://github.com/waku-org/js-waku/pull/1219 and https://github.com/waku-org/js-waku/pull/1217 being merged

**Comment by fryorcraken** [comment]
Last check point is missing: having `.send` and `.subscribe` methods directly on the `Waku` interface.

**Comment by weboko** [comment]
Last PR to close the issue https://github.com/waku-org/js-waku-examples/pull/239

**Comment by weboko** [comment]
Closed with the PR being merged
