### ISSUE TITLE
bug: eslint errors not caught

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1281]
This is a **bug report/feature or change request/support request**

## Problem

Some commits were pushed to `master `containing code against the eslint guidelines set in the repo.
It was caught when I merged `master `into a working branch locally and tried to make a commit; the precommit hook failed. Specifically eslint.

Not sure how this was allowed by our CI, and wasn't caught before.

## Proposed Solutions

TBC.

## Notes

- ref PR: https://github.com/waku-org/js-waku/pull/1280

**Comment by weboko** [comment]
Should be resolved by https://github.com/waku-org/js-waku/pull/1291
