### ISSUE TITLE
consider replacing `!!` to optional chaining in codebase

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1301]
This is a change request

## Problem

https://github.com/waku-org/js-waku/pull/1259#discussion_r1149854149

example:
``` !!nwaku && nwaku.stop();```

## Proposed Solutions

Use optional chaning instead:

`nwaku?.stop()`

**Comment by weboko** [comment]
Fixed by @fbarbu15 in https://github.com/waku-org/js-waku/blob/master/packages/tests/src/teardown.ts
