### ISSUE TITLE
write a script to update package versions to * automatically

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1346]
This is a feature request

## Problem

In our npm workspaces monorepo, we have several packages that depend on each other, and these dependencies are specified in their respective package.json files.

Currently, when we install these packages in other packages as dependencies, they are installed with their specific version numbers, for example: "@waku/build-utils": "0.2". This forces us to manually update the version numbers whenever a package is updated.

Our requirement is to automate this process such that the version numbers are always set to * instead of the explicit version number. This would enable npm to always fetch the latest version of the packages within the monorepo. For instance, we would like @waku/build-utils to be installed like: "@waku/build-utils": "*".

This issue is causing some inefficiencies in our development process as we often have to manually update the version numbers of our packages in the package.json files.

## Proposed Solutions

We could write a JS script that will recursively go through all the package.json files in our monorepo and replace the version numbers of the dependencies with * if the package belongs to our monorepo.

This script can be integrated into our build script or set up as a pre-commit hook. This will ensure that our package.json files are always up-to-date with the latest version of their dependencies within the monorepo, even before the changes are committed to the repository.

**Comment by weboko** [comment]
In short: we do not need such script since `release-please` would do this automatically in places where version is bumped. 

Relevant comment - https://github.com/waku-org/js-waku/pull/1316#discussion_r1190831633

**Comment by fryorcraken** [comment]
Regarding the discrepancy where some packages have a wildcard whereas other don't is because `release-please` only updates `dependencies` when the dependency's version is bumped.
Some packages haven't yet been release with `release-please` so the wildcard was not replaced for a version.

**Comment by fryorcraken** [comment]
Closed as discrepancy is understood but not an issue.
