### ISSUE TITLE
Default import from one package

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1353]
This is a **feature request**

## Problem

Basic usage of js-waku involved importing for a couple of packages:
- `@waku/core`
- `@waku/create`
- `@waku/utils`

See https://dev.waku.guide/browser/quick-start/

This kind be confusing for a developer.

### More Context

The js-waku mono repo aims to be modular and to enable developer to limit their dependencies.
For more context, see #1159 for more context.

However, such characteristics are not desirable for a new comer, a developer trying out Waku or attempting to use it in a hackathon.

Hence, the `@waku/create` package was created to expose some API easy to use with good defaults.

## Proposed Solutions

The proposal is for one js-waku package to be a proxy package for other packages that are expected to be used in most basic example.

`@waku/create` aimed to be said proxy package but fails at it as `@waku/core` and `@waku/utils` still need to be used.

Proposal:

1. Rename/replace `@waku/create` by a more attractive/general name. e.g. `@waku/sdk`
2. Proxy more function in new package from `@waku/core` so that all js-waku examples can be purely done by installing and importing from `@waku/sdk` (or whatever name we settle on).

- [x] `@waku/sdk` package created
- [x] Release `@waku/sdk`
- [ ] Use `@waku/sdk` in examples
- [x] Removed forced version from release-please config https://github.com/waku-org/js-waku/issues/1353#issuecomment-1576630666

## Notes

Cc @hackyguru @LordGhostX

**Comment by weboko** [comment]
Keeping issue open to remove (forced version)[https://github.com/waku-org/js-waku/blob/951ebdac9d5b594583acf5e4a21f6471fa81ff74/release-please-config.json#L19] after next release.

**Comment by fryorcraken** [comment]
FYI I defined next steps for this issue in the description

**Comment by fryorcraken** [comment]
Let's try to have remaining items done next week.

**Comment by weboko** [comment]
`@waku/sdk` is released and I will complete the transition of a basic example to it early next week

**Comment by weboko** [comment]
Basic examples are using `@waku/sdk` now. So we can start pointing it out in our docs. Meanwhile I started transitioning `eth-pm` and other `React` based examples. 

cc: @LordGhostX

**Comment by weboko** [comment]
The last example to update is `relay-angular-chat` and it is not that straightforward because of the inconsistency of internal types. 
Will be addressed here a bit later - https://github.com/waku-org/js-waku-examples/pull/246

**Comment by weboko** [comment]
Closing in favor of https://github.com/waku-org/js-waku-examples/issues/247
