### ISSUE TITLE
How to build my own waku-relay, waku-store?

### ISSUE THREAD

**Issue by liuqixing** [waku-org/js-waku#1401]
How to build my own waku-relay, waku-store?

**Comment by weboko** [comment]
@liuqixing can you, please, elaborate on what you mean by `build my own`? 

Do you want to implement a specification?
- if so this is a collection of specification we are working on: https://rfc.vac.dev/


Or you want to use `waku` in your program? 
- if so in this repo your will be able to find examples for `relay` and `store` https://github.com/waku-org/js-waku-examples#readme

If you have some questions during work on Waku - feel free to ask them in our Discord https://discord.com/channels/1110799176264056863/1111541029309534249

**Comment by weboko** [comment]
For that you can reference current implementations of Waku:
- https://github.com/waku-org/nwaku
- https://github.com/waku-org/go-waku

And [RFCs](https://rfc.vac.dev/)

**Comment by liuqixing** [comment]
Thank you so much again for your reply.
And, is there a deployment manual for js-Waku on the server? 
Or is there a Docker image available for download that I can directly deploy on the server?

**Comment by weboko** [comment]
@liuqixing `js-waku`'s mission for now is to be light weight node for dApps in the browser.
Thought it is possible to take `js-waku` and use in Node.js - behavior is not predictable.

For that I advice to use other implementations.
- https://github.com/waku-org/go-waku
- https://github.com/waku-org/nwaku

**Comment by weboko** [comment]
Feel free to ask following questions in our discord - https://discord.com/channels/1110799176264056863/1111541029309534249

**Comment by liuqixing** [comment]
Thank you so much for your reply!

and, Which is more stable, nwaku or go-waku, in a production environment?

**Comment by fryorcraken** [comment]
Please join our discord https://discord.waku.org for this kind of support request.
