### ISSUE TITLE
Can "Waku-store" be used as a persistent storage solution based on a p2p network?

### ISSUE THREAD

**Issue by liuqixing** [waku-org/js-waku#1404]
Can "Waku-store" be used as a persistent storage solution based on a p2p network?

**Comment by weboko** [comment]
Yup, this is the purpose of the `Waku Store protocol` 
Here are more details on it:
- https://rfc.vac.dev/spec/13/

Here are the examples you can use to see how it works:
- https://github.com/waku-org/js-waku-examples/tree/master/examples/store-reactjs-chat
- https://github.com/waku-org/js-waku-examples/tree/master/examples/store-js

**Comment by weboko** [comment]
Feel free to ask following questions in our Discord - https://discord.com/channels/1110799176264056863/1111541029309534249

**Comment by liuqixing** [comment]
thank you so much for your reply!

**Comment by liuqixing** [comment]
As far as I know, Status IM app uses the Waku library. Do you know how the persistence storage is implemented in Status IM?

**Comment by fryorcraken** [comment]
Status Mobile app currently use Waku v1 and mailservers and will migrate to Waku v2 and store servers.

Status Desktop app uses Waku v2 and store servers. The aim for Status Communities is to have 30 days of data. However, this is large amount of data and we do not recommend to expect such time period for other applicaitons as the current solution we are delivering mean reduction in decentralization.

The long term deccentralized solution is still research in progress: https://github.com/waku-org/pm/issues/21 and would most likely need the usage of a decentralized store engine such as Codex.

**Comment by liuqixing** [comment]
According to my understanding, Status Mobile App currently uses Waku v1 as a p2p-based decentralized communication method, but mail servers are centralized storage.

The centralized storage of mail servers is planned to be migrated to store servers, but I have a question, such as a user profile, settings, and other information that needs to be permanently stored, how to solve the problem of permanent persistent storage after migrating to store server?
