### ISSUE TITLE
WebSocket connection to 'wss://node-01.do-ams3.wakuv2.test.statusim.net:8000' failed: 

### ISSUE THREAD

**Issue by liuqixing** [waku-org/js-waku#1405]
ping node-01.gc-us-central1-a.wakuv2.test.statusim.net and node-01.gc-us-central1-a.wakuv2.test.statusim.net response data with 200ms average.

but there is no response on server port 8000

**Comment by fryorcraken** [comment]
This is most likely due to https://github.com/waku-org/pm/issues/23

**Comment by weboko** [comment]
Closing as it is connected to the mentioned issue. I think it is also similar to https://github.com/waku-org/js-waku/issues/1403 and if so will be covered there.
