### ISSUE TITLE
update: README

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1434]
This is a **feature request**

## Problem

The current README for this repo (js-waku), while having links for different docs/roadmaps, does not impart immediate knowledge like:
- basic theoretical concepts
- basic API usage

## Proposed Solutions

Refer to some of the repos of projects attached below to take inspiration from, and provide a good landing experience for developers on the repo and impart them with basic outline of what waku is, basic API usage, etc.

## Notes

Some good repo READMEs to refer: 
- https://github.com/expressjs/express
- https://github.com/xmtp/xmtp-js
- https://github.com/facebook/react

Especially with js-waku docs rolling out soon, this might be tackled even better! 🗡️ 

cc @LordGhostX

**Comment by weboko** [comment]
@danisharora099 considering discussion in https://github.com/waku-org/js-waku/issues/1689 what would you define for scope of this particular issue?

**Comment by weboko** [comment]
Closing in favor - https://github.com/waku-org/js-waku/issues/1689
