### ISSUE TITLE
multiple connections opened for the same peer

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1459]
This is a support request

## Problem

Instance:
js-waku is discovering the same peer, from two sources (possibly diff multiaddr?). Due to this, there are two dial requests, and websocket connections opening, for the same peer.

The first multiaddr comes from DNS Discovery, while the 2nd comes from parsing the `multiaddr` of the `peer` after its connection, and saving it in local storage for easier reconnection the next time.

Websocket URL 1: `wss://node-01.gc-us-central1-a.wakuv2.prod.statusim.net:8000/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA`
Websocket URL 2: `
wss://node-01.gc-us-central1-a.wakuv2.prod.statusim.net:8000/`

<img width="1217" alt="Screenshot 2023-08-07 at 4 56 39 PM" src="https://github.com/waku-org/js-waku/assets/35004822/74611a5f-2603-400f-919d-a0e934b2614b">

<img width="1224" alt="Screenshot 2023-08-07 at 4 56 53 PM" src="https://github.com/waku-org/js-waku/assets/35004822/bc12cd6d-be47-4442-b797-7c57d940e3ed">

## Expected 

js-waku should only open one websocket connection to one peer

**Comment by fryorcraken** [comment]
I would add that to #914 yes

**Comment by chair28980** [comment]
@danisharora099 please add this issue to #1463 items per discussion 2024-01-04
