### ISSUE TITLE
Delay during message sending

### ISSUE THREAD

**Issue by kartikchoubisa** [waku-org/js-waku#1465]
Tasks for the following issue: 
- [x] https://github.com/waku-org/js-waku/issues/1496
- [x] https://github.com/status-im/infra-nim-waku/issues/83
- [x] https://github.com/waku-org/js-waku/issues/1540
- [x] open issues to track followup work (https://github.com/waku-org/js-waku/issues/1465#issuecomment-1689150384)
----
This is a support request

## Problem

Hi, I am using the js sdk in browser, with filter protocol and light push (based on the example https://github.com/waku-org/js-waku-examples/tree/master/examples/light-js ).

I am timing the delay for sending the message, here:

```
        console.time("lightpushDelay")
        await this.node.lightPush.send(this.encoder, {
            payload: utf8ToBytes(message),
        });
        console.timeEnd("lightpushDelay")

```

```
 this.encoder = createEncoder({
            contentTopic: this.contentTopic,
            ephemeral: null,
            metaSetter: null,
        });
```

The results on running multiple times:
```
lightpushDelay: 633.656005859375 ms
waku.ts?0414:89 lightpushDelay: 594.494140625 ms
waku.ts?0414:89 lightpushDelay: 589.974853515625 ms
waku.ts?0414:89 lightpushDelay: 587.387939453125 ms
waku.ts?0414:89 lightpushDelay: 589.543212890625 ms
waku.ts?0414:89 lightpushDelay: 584.498046875 ms
waku.ts?0414:89 lightpushDelay: 587.505126953125 ms
waku.ts?0414:89 lightpushDelay: 585.93798828125 ms
waku.ts?0414:89 lightpushDelay: 597.3701171875 ms
waku.ts?0414:89 lightpushDelay: 584.76806640625 ms
waku.ts?0414:89 lightpushDelay: 796.75 ms
waku.ts?0414:89 lightpushDelay: 608.840087890625 ms
waku.ts?0414:89 lightpushDelay: 600.575927734375 ms
waku.ts?0414:89 lightpushDelay: 586.3798828125 ms
waku.ts?0414:89 lightpushDelay: 584.71484375 ms
```

How can I reduce this delay? Is there other setup that would be more useful for low latency usecase?

**Comment by fryorcraken** [comment]
> for nodes external to local network
> - creating a new stream with a peer (libp2p.newStream()) is taking roughly 50% of the total delay.
> -the other roughly 50% is being taken by pipe

Interesting, I'd probably engage some discussion with libp2p team. Let's reach out to nim-libp2p first see if they have any insights on this.
In another issue, a user suggested to re-use the same stream (a). Would be good to test that out with light push (I only tested with store).

Also, when sending a message, we create the stream lazily. One approach would be to create a stream for all protocols as soon as we connect (b), so it can be skipped when sending the message.
I suspect the stream close as soon as a reply is sent on it. If that's still hold (see (a)), then we can:
- (c) create a small pool of stream (however not we'll have to increase the max output stream limit)
- (d) refill the pool as soon as we use up a stream.

Now, regarding the poor performance of `pipe`. Not sure how to address that, probably need to dig further.
Would be better to attempt a, b, c, d first before seeing how `pipe` can be optimized.

**Comment by fryorcraken** [comment]
https://discord.com/channels/864066763682218004/1140501637232857141/1140638224939757598

Reply from nim-libp2p team (Vac discord)

> General best practice is to use a different stream for each request

> However, some libp2p implementations don't support "optimistic opening", so opening a stream will cost a RTT. nim-libp2p doesn't support it (https://github.com/status-im/nim-libp2p/issues/746), looks like js doesn't either

> 300ms RTT is a lot though, it's like Hong-Kong <=> Spain
> Maybe the fleet should be somewhere a bit more "central" to the world, like Europe
> Random sheet of "average ping to all other countries", HK is really in the bottom of that list 

![image](https://github.com/waku-org/js-waku/assets/110212804/622bbc52-b239-46c4-bade-03d0bf136ec1)


My response: 

1. For optimism selection, it is likely that several protocols are selected (eg filter and light push). Does optimist protocol selection can still apply then?
2. I think it's a good point re fleet support. We already have a node in europe (AMS) and EU. Maybe it would make sense to have a node in Singapore instead of HK of Asia. Will check with Waku team and infra
3. Something for js-waku dev. Danish,  in status-go/go-waku, the node with lowest latency is selected for store node. We should probably do the same when selecting the node for filter/lightpush/store.

**Comment by fryorcraken** [comment]
FYI, tracking it under https://github.com/waku-org/js-waku/issues/1453

**Comment by weboko** [comment]
+ add a test suit to check baseline performance

**Comment by weboko** [comment]
Closing as rest will be tracked here - https://github.com/waku-org/js-waku/issues/1521
