### ISSUE TITLE
feat: Autosharding API for req-resp protocols

### ISSUE THREAD

**Issue by chair28980** [waku-org/js-waku#1500]
This tracks the work necessary in each client to provide API(s) to applications using req-resp protocols (store, lightpush, filter, etc.) with optional pubsub topic arguments. Each client should then use autosharding to determine the associated shards on behalf of applications. Note that underlying protocols should not be affected and each client implementation should locally populate pubsub topic fields with the shards hashed from content topics received via the API.

Priority: Critical for launch

**Comment by chair28980** [comment]
https://github.com/waku-org/research/issues/3

@danisharora099 @weboko 

Per the research issue, can y'all verify this is required for JSWasku and assign ownership as necessary. Thank you!

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: derive pubsub topic from content topic in encoders/decoders when autosharding is specified
- _next_: node config should specify static sharding or autosharding. implement autosharded topics in all req-resp protocols

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: config node for static/autosharding, test all protocols against autosharding RPC endpoints on nwaku
- _next_: config application and version on node creation, only discover nodes of same shard

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: all protocols can be configured to use autosharding for determining pubsub topics
- _next_: make autosharding the default behavior when running js-waku
