### ISSUE TITLE
feat: Peer discovery with dynamic shards as dimension

### ISSUE THREAD

**Issue by chair28980** [waku-org/js-waku#1504]
Tracks work necessary to ensure that nodes can filter discovered peers according to the shards the node is currently subscribed to and for the node to update its own discoverable ENR every time its subscription set changes.

Priority: Critical for launch.

**Comment by chair28980** [comment]
https://github.com/waku-org/research/issues/3

@danisharora099 @weboko

Per the research issue, can y'all verify if this is required for JSWaku and assign ownership as necessary. Thank you!

**Comment by weboko** [comment]
Keeping unassigned for now as it is not clear if it belongs to auto/static sharding or should be done separately.

**Comment by fryorcraken** [comment]
For static sharding, we can assume that the shards do not change mid execution. so this issue would not be needed to deliver it.

**Comment by danisharora099** [comment]
The latter does not apply to js-waku as it does not change the ENR, as js-waku nodes don't participate in discv5.

The former will be resolved with #1756
