### ISSUE TITLE
feat: Service peer selection on specific shards

### ISSUE THREAD

**Issue by chair28980** [waku-org/js-waku#1506]
Currently a service peer (e.g. a store node) is either provided by the application or it expects the peer manager to suggest a suitable service peer (selectPeer()). This task focuses on the latter: peer manager should provide ability to find service peers for a specific shard, based on the content topic that the application is interested in (e.g. an API call to selectPeer(Protocol, ContentTopic)), or kick off an ad-hoc discovery process until a suitable service peer is found. Client APIs (for filter, lightpush, peer-exchange) should automatically make use of this mechanism if the application does not explicitly set the desired service peer.

Priority: critical for launch

**Comment by chair28980** [comment]
https://github.com/waku-org/research/issues/3

@danisharora099 @weboko

Per the research issue, can y'all verify if this is required for JSWaku and assign ownership as necessary. Thank you!

**Comment by chair28980** [comment]
Closing per discussion during js-waku pm 2024-01-03.

Moving to triage, this issue has been resolved, please add reference to issues before closing.

**Comment by danisharora099** [comment]
This issue should be resolved with #1756
