### ISSUE TITLE
update release process to make releases for commits 

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1543]
## Problem
We currently make releases for the `master` HEAD every month. This introduces delays to test the functionality as we need to do a release to use the new HEAD.

## Proposed Solutions
The proposal is to release commits that are merged to `master` tagged with their commit hash or even make nightly releases perhaps.
This allows consumers (and us) to be able to test these functionalities outside of the scope of js-waku with ease.

## Notes
While some solutions like building `js-waku` locally and using the build files directly are still possible, they are not as frictionless of a process.

**Comment by weboko** [comment]
_next step_:
- [ ] add `beta` or `next` release from the master on each commit;

@danisharora099 why is it a priority?

**Comment by weboko** [comment]
I agree it should be done rather early, should be useful

**Comment by weboko** [comment]
TODO: 
- [ ] add CI script & version bump;
- [ ] since versions inside of packages do not bump (yet) - check if it works in general;

**Comment by fryorcraken** [comment]
I'd suggest to make PR for merged PRs, not all commits.

**Comment by weboko** [comment]
@fryorcraken do you mean similarly how `release-please` is working?
It creates PR after merging which release happens.

**Comment by fryorcraken** [comment]
> @fryorcraken do you mean similarly how `release-please` is working? It creates PR after merging which release happens.

My input was just to release for specific PR merge commit I guess. not every commit of the feature branch.

**Comment by weboko** [comment]
Addressing it here https://github.com/waku-org/js-waku/pull/1702
