### ISSUE TITLE
only allow secure websockets on transport 

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1547]
This is a **bug report/feature or change request/support request**

## Problem

js-waku currently filters and tries to dial all peers that support websockets on the transport level. this leads to a lot of failures when dialing from browsers.

## Proposed Solutions

we can perhaps limit that to only allow secure websockets (`wss`), but allow non-secure websockets (`ws`) on `localhost` if possible.

## Notes

- ref: https://github.com/orgs/waku-org/projects/2/views/1?pane=issue&itemId=37511644

**Comment by weboko** [comment]
Moving to in progress as some work has been done by @adklempner:
- https://github.com/waku-org/js-waku/pull/1989
- https://github.com/waku-org/js-waku/pull/1983
