### ISSUE TITLE
chore: split CI into separate chunks 

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1548]
This is a **change request**

## Problem

`nwaku` depends on some of our [CI steps](https://github.com/waku-org/js-waku/pull/1541) and the first solution was to use `workflow_call`. This is not ideal because now they have all of the steps from `js-waku` CI and not to run all of them we had to clutter code a bit with extra conditions.

## Proposed Solutions

Split `ci.yml` into chunks so that they can be consumed or research other options (clone `js-waku` & inject `nwaku` through `process.env` e.g).

## Notes

Original PR - https://github.com/waku-org/js-waku/pull/1541

**Comment by weboko** [comment]
cc @fbarbu15 @vpavlin

**Comment by fbarbu15** [comment]
Added this PR for the splitting of the CI: https://github.com/waku-org/js-waku/pull/1566

**Comment by fbarbu15** [comment]
Applied changes to a forked nwaku repo: https://github.com/nwaku-test-org/nwaku/actions/runs/6170532712
PR: https://github.com/nwaku-test-org/nwaku/pull/18
