### ISSUE TITLE
Subscribe fails with `Error subscribing to peer`

### ISSUE THREAD

**Issue by agazso** [waku-org/js-waku#1562]
This is a **bug report**

## Problem

I have an app and it subscribes to several topics when it starts. It usually works but sometimes it returns with this error:
```
Error subscribing to peer: 16Uiu2HAm8gXHntr3SB5sde11pavjptaoiqyvwoX3GyEZWKMPiuBu for content topics: /wakuobjects-playground/1/private-message/e8cb81467b1bf57d41970d3e87bd9138f4f6ed455fde9beb4acc18f89c46cd84: TypeError: Cannot read properties of undefined (reading 'slice')
```
(See full stack trace below). I am not sure how to deal with this. There were four subscriptions and three other `subscribe` calls were successful. I also print out the waku connection status and it was reported as connected at the time of the call, but 200 milliseconds later it got disconnected (as in it got `peer:disconnected` event from `libp2p` and `libp2p.getConnections().length === 0`). 

## Proposed Solutions

I think it would be better if the library checked for the value before trying to call `slice` on it. And if it is undefined then throw an exception which describes what happened or at least the documentation could include it along with some instructions what to do in that case (for example repeat the `subscribe` call or something).

## Notes

`@waku/sdk` version 0.0.18
Running on Node v18.17 on Linux
Connected to nwaku 0.18

Full stack trace:
```
Error: Error subscribing to peer: 16Uiu2HAm8gXHntr3SB5sde11pavjptaoiqyvwoX3GyEZWKMPiuBu for content topics: /wakuobjects-playground/1/private-message/e8cb81467b1bf57d41970d3e87bd9138f4f6ed455fde9beb4acc18f89c46cd84: TypeError: Cannot read properties of undefined (reading 'slice')
    at Subscription.subscribe (/home/attila/Projects/LogosLab/waku-objects-playground/node_modules/.pnpm/@waku+core@0.0.22_@multiformats+multiaddr@12.1.3_libp2p@0.45.9/node_modules/@waku/core/src/lib/filter/index.ts:110:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Filter.subscribe (/home/attila/Projects/LogosLab/waku-objects-playground/node_modules/.pnpm/@waku+core@0.0.22_@multiformats+multiaddr@12.1.3_libp2p@0.45.9/node_modules/@waku/core/src/lib/filter/index.ts:309:5)
    at subscribe (/home/attila/Projects/LogosLab/waku-objects-playground/src/lib/adapters/waku/waku.ts:73:22)
    at main (/home/attila/Projects/LogosLab/waku-objects-playground/src/lib/adapters/waku/bot.ts:75:3)
```

**Comment by weboko** [comment]
So, for now, adding error handling for that case to see what actually breaks. 
Didn't manage to repro in any of our examples (with peers being dropped) so I guess this is some kind of bad timing that causes this particular problem.

@agazso could you share a minimal repro setup, please?

**Comment by agazso** [comment]
> So, for now, adding error handling for that case to see what actually breaks. Didn't manage to repro in any of our examples (with peers being dropped) so I guess this is some kind of bad timing that causes this particular problem.
> 
> @agazso could you share a minimal repro setup, please?
> 
> Once I understand I can add unit test for that case.

I accidentally found a minimal reproduction by using `waku.stop()` which my code originally did not have, so that's not the only way to trigger the issue. I tested this with running `nwaku` version 0.20.0 locally with docker.  

If the `await unsubscribe()` line is removed it triggers a similar error than in https://github.com/waku-org/js-waku/issues/1553

```typescript
import { Protocols } from "@waku/interfaces"
import { createDecoder, createLightNode, waitForRemotePeer } from "@waku/sdk"
import { multiaddr } from '@multiformats/multiaddr'

// change the id of the peer
const peerMultiaddr = multiaddr(
	'/ip4/127.0.0.1/tcp/8000/ws/p2p/16Uiu2HAm53sojJN72rFbYg6GV2LpRRER9XeWkiEAhjKy3aL9cN5Z',
)

main()

async function main() {
    const waku = await createLightNode()    
    await waku.start()
    await waku.dial(peerMultiaddr)
    await waitForRemotePeer(waku, [Protocols.Filter, Protocols.LightPush, Protocols.Store])

    const messageDecoder = createDecoder('abc')
    const unsubscribe = await waku.filter.subscribe([messageDecoder], () => { /* */ })

    await unsubscribe()

    await waku.stop()
}

```

**Comment by weboko** [comment]
My guess now is that recent changes fix the problem and currently it fails on `.dial` call so should be possible to catch such an issue.
