### ISSUE TITLE
Generate and attach RLN proofs when using light push

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1601]
## Problem

RLN proofs need to be generated and attached to Waku messages sent over lightpush

## Acceptance Criteria

- [ ] Integrate RLN to `@waku/sdk` and update the API to ensure proofs area passed.

## Notes

RLN does not need to be used by default from the get go but we need to start adding it to the sdk and easily enable it.

**Comment by weboko** [comment]
Blocked by https://github.com/waku-org/js-rln/issues/69

**Comment by weboko** [comment]
Making it part of `sdk` will be addressed in https://github.com/waku-org/js-rln/issues/76
Improvements for make generation of proofs are done under - https://github.com/waku-org/pm/issues/109
