### ISSUE TITLE
Test report with history

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/js-waku#1605]
This is a **feature request** 

## Problem

It's hard to debug test from the github actions console output, especially if you want to look on the history of a test (for flakyness)

## Proposed Solutions

Using a proper testing reporting tool like [allure](https://docs.qameta.io/allure/) (for [mocha](https://www.npmjs.com/package/allure-mocha)) makes debugging much easier and gives testing in general more visibility

It's free, works fine with all kinds of test runners: mocha, karma, playwright test, pytest and much more

Can be easily integrated with github actions and deployed with github pages (wich is free since this is a public repo)

Supports adding attachments (logs for each test, screenshot/videos for UI interactions) and links at test level

ex: https://simple-elf.github.io/allure-report-action/26/

**Comment by weboko** [comment]
@fbarbu15 I think we can resolve this issue as we have https://waku-org.github.io/allure-jswaku/5676/# now

**Comment by weboko** [comment]
Marking as resolved as we have `allure` already

@fbarbu15 re-open if I am wrong
