### ISSUE TITLE
Filter subscribe on 2 different nwaku nodes doesn't work reliable

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/js-waku#1606]
This is a **bug report**

## Problem

- Have a  js-waku ligh node and 2 nwaku nodes.
- From js-waku create 2 filter subscription objects, one for each nwaku node.
- Send messages for both subscriptions.

50% of the time the message send for the 2nd subscription is lost

I tested this by having the DefaultPubSubTopic on both nwaku nodes but also having different pubSubTopics (in the context of static sharding) and the issue reproduces in both cases.

I have a test that reproduces the issue [here](https://github.com/waku-org/js-waku/blob/master/packages/tests/tests/filter/subscribe.node.spec.ts#L310). Test fails 50% of the time at `expect(await messageCollector.waitForMessages(2)).to.eq(true);` because only the 1st message is detected. In order to reproduce this you need to disable the mocha retry mechanism from .mocharc

**Comment by fbarbu15** [comment]
Same issue with Store protocol

**Comment by fryorcraken** [comment]
Will be done as part of https://github.com/waku-org/js-waku/issues/914

**Comment by chair28980** [comment]
Closing in favor #1463
