### ISSUE TITLE
Peer exchange throwing uncaught exceptions

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1639]
This is a **bug report**

## Problem

https://discord.com/channels/1110799176264056863/1160201584215609484/1160201810477334668 (Waku Discord

**Comment by fryorcraken** [comment]
May need to do tests like https://github.com/waku-org/js-waku/pull/1584

**Comment by weboko** [comment]
The hacker that was complaining about it could've had broken setup or some other issue in their code.

I would better address it in the scope of https://github.com/waku-org/js-waku/issues/1665 and not focus on it as `peer exchange` only issue.
