### ISSUE TITLE
Use REST API in CI

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1644]
This is a **change request**

## Problem

js-waku tests use the JSON RPC API of go-waku and nwaku nodes.

The intent is to deprecate the JSON RPC API in favour of the REST API.

Efforts has been made to have feature equivalence of the REST API with JSON RPC API:
- https://github.com/waku-org/nwaku/issues/1076
- https://github.com/waku-org/go-waku/issues/264

Equivalence reached for nwaku, need to confirm status for go-waku.

## Proposed Solutions

Use REST API instead of JSON RPC API in js-waku tests.
May need to keep JSON RPC API until work done in go-waku.

## Notes

Maybe interesting to create a separate package in the monorepo to provide an "agnostic" consumer the API, auto-generated from the openapi yaml files with maybe a think layer of utils to convert objects from js-waku to API.

**Comment by weboko** [comment]
It is used already, resolving.
