### ISSUE TITLE
feat: better support for development

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1665]
This is a **support request**

## Problem

This issue is rather generic and includes two things to address: better development compatibility and suppression of useless errors.

I saw these problem occurring during `basic flow`:
- [x] send couple of `lightPush` messages;
- [x] make couple of `filter` subscriptions;
- [x] request some `store` messages;
- [x] run `waku relay` and send / get some messages; 
- [x] wait for 5-10-20 minutes doing nothing on the page;

### Better development 

During hackathon many builders complained about errors that were bothering their development routine. It was happening due to random errors being thrown and either not caught or being caught but propagated up the stack. When such a thing happens - build in development mode show special screen with message of the error.

This problem can be addressed by creating basic apps and running `basic flow`
- [x] check if NextJS;
- [x] check latest `create-react-app`;

### Useless errors 

This one is quite generic but we should start investigating it and addressing. 
Problem here is that in console there are many errors that are misleading people new to project (see below).

TODO:
- [x] run `basic flow` and check errors in console;
- [ ] if they have no value - document here and try to suppress; 

![image](https://github.com/waku-org/js-waku/assets/118575614/95d8612b-df26-429a-9498-4ecba59a9111)

## Proposed Solutions

Useless errors should be suppressed and not shown to console or caught by `js-waku` if they originate from beneath. 
This should prevent development mode showing error screens when not needed and will help novice people not getting lost in understanding what is a real error and what is not.

**Comment by vpavlin** [comment]
My way to reproduce some nasty behaviour in react app

1. Clone https://github.com/vpavlin/js-waku-helpers 
2. `cd example & npm start` 
3. Open the app in multiple tabs
4. Wait for both server and client to be ready (server prints `ready`, client is ready when `New game` is clickable)
4. Fill in the game name and user name, hit `New game`
5. You can also fill in user name in another tab and hit `Join` button games it captured from Waku

I observe multiple errors which bubble up with various  frequency

```
Failed to get a connection to the peer
The operation was aborted
stream reset
stream ended before 1 bytes became available
Uncaught (in promise) CodeError: Too many outbound protocol streams for protocol "/vac/waku/filter-subscribe/2.0.0-beta1" - limit 64
...
```

**Comment by weboko** [comment]
Moving to priority due to it being highly requested and important to overall satisfaction.
Will start working on it in a day or so.

**Comment by weboko** [comment]
Weekly update:
- _achieved_: experimented with [Next.js app](https://github.com/waku-org/js-waku-examples/pull/281);
- _next_: looking for ways to mitigate errors in console or catch others;

**Comment by weboko** [comment]
Weekly update:
- _achieved_: by going through basic flow identified errors that can or cannot be ignored;
- _next_: working on improving log errors, aiming to complete in couple of days;
