### ISSUE TITLE
feat: node connection state

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1666]
This is a **feature request**

## Problem

It is problematic for novice people to check if browser node is connected to `Waku network`

## Proposed Solutions

Enable users to easily check online/offline status and maybe other things. Good reference could be current browser behavior. 

```ts
console.log('Initially ' + (window.navigator.onLine ? 'on' : 'off') + 'line');

window.addEventListener('online', () => console.log('Became online'));
window.addEventListener('offline', () => console.log('Became offline'));
```

**Comment by adklempner** [comment]
We may want both. I can imagine scenarios where it's more convenient to poll the network status as versus receiving it as an event, and vice-versa.

**Comment by adklempner** [comment]
Is `ConnectionManager` the right place for this functionality?

Here's what I'm thinking of adding:
```typescript
  private online: boolean = false;

  public isConnected(): boolean {
    return this.online;
  }

  private toggleOnline(): void {
    if (!this.online) {
      this.online = true;
      this.dispatchEvent(new Event("waku:online"));
    }
  }

  private toggleOffline(): void {
    if (this.libp2p.getPeers().length == 0) {
      this.online = false;
      this.dispatchEvent(new Event("waku:offline"));
    }
  }
```

`toggleOnline` would be called at the end of the existing handler for `peer:connected`, and `toggleOffline` would be called at the end of the existing handler for `peer:disconnected`

This assumes that having a single peer is enough to be considered "online". In the future we may change it if need be (e.g. if node is setup to use autosharding, it should be connected to at least one peer for each shard to be considered online)

What I'm not sure about is a clean way to pass an event listener for the newly dispatched events (`waku:online` and `waku:offline`) from `WakuNode` to the `ConnectionManager`.

**Comment by weboko** [comment]
> Is ConnectionManager the right place for this functionality?

I think for functionality but exposed it should be on the root level as we'd like to have it on the surface. 

Overall to me it seems as good approach, I would also use these events.

@danisharora099 what do you think?

**Comment by adklempner** [comment]
I changed the way `toggleOffline` determines if there are any peers connected, because the array returned by `this.libp2p.getPeers()` was not updating after `peer:disconnected` events were dispatched. I added a function to `KeepAliveManager` that determines if there any connections if any relay or ping timers are present: https://github.com/waku-org/js-waku/pull/1719/files#diff-47f53ecbbc63fddf37d939149e70131b808afe18c0ce785c9033e1f1cf5f18c0R114

**Comment by adklempner** [comment]
> `ConnectionMnaager` seems like the right place to include this. While I see no direct harm with using `KeepAliveManager` and the pings to gauge connectivity, I'd use `libp2p.getConnections()` instead.

@danisharora099 I tried using that function but it always returned an array of length 0 after two `peer:connect` events were dispatched in the test. Maybe the way I'm setting up the preconditions in the test doesn't match production conditions? Is there something that needs to happen besides dispatching a `peer:connect` event for the connection to be added to the array returned by `libp2p.getConnections()`? Here's the test: https://github.com/waku-org/js-waku/blob/2e34b07a2effd56cdeace395c6b3510653d10b44/packages/tests/tests/connection_manager.spec.ts#L200

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: modified `ConnectionManager` to track connection state. exposed through read function and new event 
- _next_: resolve any remaining feedback

**Comment by adklempner** [comment]
> > `ConnectionMnaager` seems like the right place to include this. While I see no direct harm with using `KeepAliveManager` and the pings to gauge connectivity, I'd use `libp2p.getConnections()` instead.
> 
> @danisharora099 I tried using that function but it always returned an array of length 0 after two `peer:connect` events were dispatched in the test. Maybe the way I'm setting up the preconditions in the test doesn't match production conditions? Is there something that needs to happen besides dispatching a `peer:connect` event for the connection to be added to the array returned by `libp2p.getConnections()`? Here's the test:
> 
> https://github.com/waku-org/js-waku/blob/2e34b07a2effd56cdeace395c6b3510653d10b44/packages/tests/tests/connection_manager.spec.ts#L200

This could be better tested by actually running one nwaku node and dialing it from the js waku node being tested. This should establish an actual connection and it will appear under `libp2p.getConnections()`

To disconnect, use this function https://github.com/libp2p/js-libp2p/blob/13a870cbef326a3a3b3c55b886c2109feaa2b628/packages/libp2p/src/libp2p.ts#L301

**Comment by danisharora099** [comment]
this issue is resolved
