### ISSUE TITLE
fix: Store digest changes

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/js-waku#1681]
This is a **change request**

## Problem

There are some changes regarding store digest in [gowaku](https://github.com/waku-org/go-waku/pull/820) and [nwaku](https://github.com/waku-org/nwaku/pull/2132) that makes the js-waku tests fail with INVALID_CURSOR

## Proposed Solutions
Similar changes should be done on js-waku side:

[this ](https://github.com/waku-org/js-waku/blob/master/packages/core/src/lib/store/index.ts#L408-L430) function needs to be updated to add the pubsub topic and meta field

**Comment by fryorcraken** [comment]
Is this a bug, or this work under https://github.com/waku-org/nwaku/issues/2112 or both?

**Comment by fbarbu15** [comment]
> Is this a bug, or this work under [waku-org/pm#64](https://github.com/waku-org/pm/issues/64) or both?

It's a change on nwaku side that breaks the js-waku <-> nwaku interop store tests.
I've asked on discord and it turns out that there was some changes in nwaku and gowaku that needed to be done in js-waku as well. @weboko  suggested I create a ticket to track them https://discord.com/channels/1110799176264056863/1166008262051778600

**Comment by ABresting** [comment]
> in context to [#1691 (comment)](https://github.com/waku-org/js-waku/pull/1691#issuecomment-1821273534), what is the path forward here? @ABresting

@danisharora099 Thanks for pointing out this open issue, as mentioned in the PR above, this issue is also being closed without any code changes against it, jsWaku operations are running normally now. More details on this [here](https://github.com/waku-org/research/issues/46)
