### ISSUE TITLE
feat: ability to flag words based on patterns

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1704]
This is a **feature request*

## Problem

Our current word/spelling check library, cSpell, does not offer a feature to *flag* words based on patterns/regex.

This introduced leaks that need to be manually resolved: https://github.com/waku-org/js-waku/pull/1703

## Proposed Solutions

- change word-check library from cSpell to a library that supports flagging words with patterns
- write a utility script that parses & replaces words based on a pattern

**Comment by weboko** [comment]
Do we even need this `cspell`? 😅

**Comment by adklempner** [comment]
https://cspell.org/configuration/patterns/

**Comment by chair28980** [comment]
Action items per js-waku pm 2023-11-07

- research existing solutions
- implement homegrown solution (less desirable) -- will require ongoing maintenance. 

---

Danish: 
- We should come to consensus on how we should handle theses cases.

**Comment by adklempner** [comment]
I have an MR which adds an eslint rule that uses regex to forbid any identifiers which contain `pubSub` or `PubSub`: https://github.com/waku-org/js-waku/pull/1709

I think it should cover most cases.
