### ISSUE TITLE
No error is returned from lightpush if a peer is full

### ISSUE THREAD

**Issue by agazso** [waku-org/js-waku#1715]
This is a **feature or change request**

## Problem

I ran into a problem that I had a peer that had a full disk and `lightPush.send` returned no error, but the data returned from `store.queryGenerator` was empty.

More specifically there were no `errors` in `SendResult`, and the peer was in `recipients`.

## Proposed Solutions

It would be better to return either `REMOTE_PEER_FAULT` or `REMOTE_PEER_REJECTED` if the peer is full and cannot store data. I haven't checked the code, but most likely this issue affects not only `js-waku` but also `nwaku` (and possibly `go-waku` as well).

## Notes

- js-waku version: `"@waku/sdk": "^0.0.20"`
- Environment (browser software and version, system software and version): Firefox & Chromium on Linux
- Nodes connected to: nwaku 0.21.1

**Comment by fryorcraken** [comment]
Is the full disk on nwaku side or nodejs side?

**Comment by agazso** [comment]
On the nwaku side.

**Comment by fryorcraken** [comment]
@waku-org/nwaku-developers happy if I transfer the issue over?

@agazso do you have logs for nwaku? waht DB did you use ? SQlite or PostgreSQL:?

**Comment by agazso** [comment]
> @agazso do you have logs for nwaku? waht DB did you use ? SQlite or PostgreSQL:?

Not sure if I still have the logs. The DB is Sqlite.

**Comment by chair28980** [comment]
Transferring issue to nwaku repo.

**Comment by chair28980** [comment]
Closing in favor of https://github.com/waku-org/nwaku/issues/2335
