### ISSUE TITLE
Lightpush send fails when using with ECIES encoder

### ISSUE THREAD

**Issue by agazso** [waku-org/js-waku#1716]
This is a **bug report**

## Problem
I am trying to use ECIES encryption from the `@waku/message-encryption` package. When I try to send with lightPush I get `Generic error`. It works well with the symmetric encryption.

## Notes

- js-waku version: `"@waku/message-encryption": "^0.0.22","@waku/sdk": "^0.0.20"`
- Environment (browser software and version, system software and version): Firefox & Chromium on Linux
- Nodes connected to: nwaku 0.21.1

Example code:
```typescript
import { Protocols } from '@waku/interfaces'
import { createLightNode, waitForRemotePeer } from '@waku/sdk'
import { hexToBytes } from '@waku/utils/bytes'
import { createEncoder } from '@waku/message-encryption/ecies'
import { multiaddr } from '@multiformats/multiaddr'

// change the id of the peer
const peerMultiaddr = multiaddr(
	'/ip4/127.0.0.1/tcp/8000/ws/p2p/16Uiu2HAm53sojJN72rFbYg6GV2LpRRER9XeWkiEAhjKy3aL9cN5Z',
)

main().catch(console.error)

async function main() {
	const waku = await createLightNode({})
	await waku.start()
	await waku.dial(peerMultiaddr)
	await waitForRemotePeer(waku, [Protocols.Filter, Protocols.LightPush, Protocols.Store])

	const contentTopic = `/test/1/a/proto`
	const payload = new Uint8Array([0])
	const publicKey = hexToBytes('02e4985b721113c1d7590db243b482a5ba58c9425764fd9f74b1bad704c3b56951')
	const encoder = createEncoder({ contentTopic, publicKey })
	const sendResult = await waku.lightPush.send(encoder, { payload })
	console.log({ sendResult })
}
```

Output:
`{ sendResult: { recipients: [], errors: [ 'Generic error' ] } }`

**Comment by fryorcraken** [comment]
I can see an exception being raised in the logs when I reproduce it:

```
waku:error:light-push Failed to prepare push message Error: Bad public key, it should be 65 bytes but it's actually 33 bytes long
```

How did you generate the keypair?

**Comment by agazso** [comment]
I use https://github.com/paulmillr/noble-curves and the public key is 33 bytes because it is compressed. I tried with an uncompressed key and it works.

However before this issue is closed I would like to know how did you get this error. I only got `Generic error` and no exception was raised and that was not helpful, but if I got the error that you got it would have been much more clear what the issue is and how to fix it.

**Comment by fryorcraken** [comment]
> I use [paulmillr/noble-curves](https://github.com/paulmillr/noble-curves) and the public key is 33 bytes because it is compressed. I tried with an uncompressed key and it works.
> 
> However before this issue is closed I would like to know how did you get this error. I only got `Generic error` and no exception was raised and that was not helpful, but if I got the error that you got it would have been much more clear what the issue is and how to fix it.

in my case I reproduced it in local tests using nodejs with debug env setup: https://docs.waku.org/guides/js-waku/debug-waku-dapp#enabling-debug-logs

Regarding using noble-curves. We recently exposed more of the crypto tooling so you can use everything directly from Waku: https://github.com/waku-org/js-waku/pull/1728  cc @weboko

**Comment by agazso** [comment]
> in my case I reproduced it in local tests using nodejs with debug env setup: https://docs.waku.org/guides/js-waku/debug-waku-dapp#enabling-debug-logs

Cool, I did not know about debug logging in waku.
