### ISSUE TITLE
feat: make autosharding default node behavior

### ISSUE THREAD

**Issue by adklempner** [waku-org/js-waku#1749]
This is a **feature or change request**

## Problem

The default configuration for a js-waku node uses static sharding with a default pubsub topic. We expect the default behavior to be autosharding, which requires specifying `application` and `version` as otherwise there is no sensible default pubusb topic.

## Proposed Solutions

Update constructors for the node and all protocols to default to autosharding and require providing `application` and `version` parameters.

**Comment by fryorcraken** [comment]
I suggest the following strategy to make the migration smooth:
- keep `createLightNode` as it is: default to default pubsub topic and supports named space
- mark `createLightNode` as deprecated: devs can use it but they get a warning
- New method `createNode` that only support static and autosharding, default to autosharding.

This gives dev more time to migrate.
It also gives us more time to migrate the tests and examples.

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: open PR to reintroduce (but deprecate) name sharding alongside auto/static sharding without breaking APIs
- _next_: update all examples to use autosharding
- _blocker_: need review on https://github.com/waku-org/js-waku/pull/1723

**Comment by adklempner** [comment]
**Weekly Update**

- _achieved_: umerged PR that implements autosharding after feedback. PR to reintroduce named sharding ready for review
- _next_: update all examples to use autosharding
