### ISSUE TITLE
allow user to pass content topic to createSubscription

### ISSUE THREAD

**Issue by adklempner** [waku-org/js-waku#1764]
This is a **feature or change request**

## Problem

Currently, creating a subscription via filter requires passing an instance of `SingleShardInfo`. This is not user friendly when using autosharding. The user should be able to just pass in the content topic in order to create a subscription.

## Proposed Solutions

Modify `createSubscription` to accept a content topic and convert it to the proper pubsubTopic within the function itself.

## Notes

Related to #1500

**Comment by chair28980** [comment]
Related to #1814

**Comment by danisharora099** [comment]
> creating a subscription via filter requires passing an instance of SingleShardInfo

it takes either `SingleShardInfo` or the type `PubsubTopic` which is string, which seems to be relevant for autosharding. what am i missing?
