### ISSUE TITLE
Investigate Metadata Protocol test failing on nwaku latest

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/js-waku#1765]
This is a **bug report**

## Problem
Failing test is **[same cluster, different shard: nodes connect](https://github.com/waku-org/js-waku/blob/master/packages/tests/tests/metadata.spec.ts#L62-L98)** and fails at **waku.libp2p.dialProtocol**
This test passes on **wakuorg/nwaku:v0.22.0** but fails on newer versions like **harbor.status.im/wakuorg/nwaku:latest**
Error I see is **stream ended before 1 bytes became available**

**Comment by danisharora099** [comment]
I'm curious what changed between v0.22 and the RC for 0.23 -- the test passes for v0.22

**Comment by Ivansete-status** [comment]
> I'm curious what changed between v0.22 and the RC for 0.23 -- the test passes for v0.22

Hey @danisharora099 @fbarbu15 ! Thanks for that. What precise rc did you use to test it?
Yesterday we created the `v0.23.0-rc.1` with changes around peer_manager, and I wonder if the issue happens with that as well.

**Comment by fbarbu15** [comment]
It fails also on v0.23.0-rc.1. Added logs for all 3 versions:
[docker_logs_nwaku_v22_test_passes.log](https://github.com/waku-org/js-
waku/files/13724694/docker_logs_nwaku_v22_test_passes.log)
[docker_logs_nwaku_v23_test_fails.log](https://github.com/waku-org/js-waku/files/13724695/docker_logs_nwaku_v23_test_fails.log)
[docker_logs_nwaku_latest_test_fails.log](https://github.com/waku-org/js-waku/files/13724697/docker_logs_nwaku_latest_test_fails.log)

**Comment by Ivansete-status** [comment]
Thanks so much @fbarbu15 @danisharora099 !
The following PR fixes the issue:
https://github.com/waku-org/nwaku/pull/2312
Therefore, I think this can be closed.
Cheers

**Comment by fbarbu15** [comment]
I've run the failing tests locally with `quay.io/wakuorg/nwaku-pr:2312` and the tests pass. Closing
Thanks
