### ISSUE TITLE
use Waku Network cluster id  as default for autosharding

### ISSUE THREAD

**Issue by adklempner** [waku-org/js-waku#1776]
This is a **feature or change request**

## Problem

To setup a node for autosharding, a user needs to explicitly specify both content topics and a cluster id to determine the pubsub topics. According to the [RFC](https://rfc.vac.dev/spec/64/#network-shards), the Waku Network always uses a cluster id of 1.

## Proposed Solutions

Modify any functions that accept sharding parameters to accept a list of content topics without a cluster id, in which case the default cluster id should be set.

**Comment by chair28980** [comment]
Internal dogfooding issue: https://github.com/waku-org/js-waku/issues/1812
