### ISSUE TITLE
Decouple sharding logic from internal classes to SDK

### ISSUE THREAD

**Issue by adklempner** [waku-org/js-waku#1808]
This is a **feature or change request**

## Problem

There are currently three sharding types/interfaces used across several classes:
1. `ShardingParams`: input by consumer when creating a node to configure it for sharding (part of `ProtocolCreateOptions`)
2. `ShardInfo`: represents cluster ID and shard indexes supported by a node. Encoded/decoded from/to the ENR, used for metadata and peer discovery.
3. `SingleShardInfo`: similar to above but only ever specifies a single shard index. Used to create message encoder/decoders and subscriptions.

`ShardingParams` is used in all the functions for creating nodes via the SDK, as well as all the constructors for `Waku`, `BaseProtocol`, `Relay`, `Filter`, `Store`, and `LightPush`. In these constructors, the logic is basically identical: the `ShardingParams` are used to validate and generate pubsub topics. Once the pubsub topics are generated, they are stored in the class and the `ShardingParams` are no longer used.

If any changes need to be made to `ShardingParams` or the logic of how pubsub topics are generated, it potentially needs to be updated in 6 constructors, even though internally all these classes just use pubsub topics and do not store sharding information in any form.

## Proposed Solutions

Remove conversion of `ShardingParams` from `Waku`, `BaseProtocol`, `Relay`, `Filter`, `Store`, and `LightPush`. Instead, just pass the pubsub topics in the constructor.

This may involve removing the `shardInfo` field from `ProtocolCreateOptions` and instead using an additional argument for each `createX` function in the SDK.

## Notes

The main motivation behind this change is to separate responsibility of handling sharding settings from the core protocol classes, as these should be able to change independently of one another.

**Comment by danisharora099** [comment]
Agree with this approach! Will help manage state internally.
