### ISSUE TITLE
test: nwaku nodes started on The Waku Network requires a RPC endpoint

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1914]
## Problem

Within our tests suite, we have tests that also attempt connection with nodes started on cluster ID = 1  and after the v0.26.0 update, it **expects** a RPC endpoint passed along to fetch contract re data.

## Proposed Solutions

- Use a public RPC endpoint that we can also push to GH without any security concerns
- Use environment variables for the RPC endpoint

**Comment by rymnc** [comment]
something that is tangentially related to this issue, please ensure that the rln_tree is persisted across runs so the nwaku nodes finish sync and startup quicker

**Comment by weboko** [comment]
Moving to Priority as we need to address it sooner than later.

**Comment by weboko** [comment]
@fbarbu15 can you, please, give your input on this issue? 

In particular, if we foresee many tests in future to use this?

**Comment by weboko** [comment]
Summarizing - we foresee such tests in `js-waku` in future but not now.
@adklempner merged the PR and the job is now skipped in CI.

Once it is needed I think QA team will re-enable this step and will update with needed changes.

Closing as complete.
