### ISSUE TITLE
bug: lightPush is not able to keep node connections

### ISSUE THREAD

**Issue by vpavlin** [waku-org/js-waku#1966]
bug report

## Problem

Similarly to my issues with Filter (https://github.com/waku-org/js-waku/issues/1923), when I keep a `light-js` example running for ~15 minutes with clean `waku:peers` localStorage, LightPush "breaks" - I get an error message when attempting to `send` in debug logs:

```
waku:warn:light-push No peers found. Ensure you have a connection to the network. +0ms
```

After reload it took less then 5 minutes to the lightnode to lose all the lightpush peers - started with 3

![Screenshot from 2024-04-19 10-52-15](https://github.com/waku-org/js-waku/assets/4759808/a93bb22e-cdb8-4f18-96ed-3f0146c25bab)

3 minutes later there was only 1 peer
![Screenshot from 2024-04-19 10-54-21](https://github.com/waku-org/js-waku/assets/4759808/a99c2559-1003-496f-93e5-e6a83be62b68)

And a minute later there were no peers.

It does not seem to recover from this state

## Proposed Solutions

- Ensure that js-waku attempts to reconnect to a peer after losing a connection

## Notes

- js-waku version: 0.0.25-fd60cc2.0

**Comment by adklempner** [comment]
I modified connection manager such that it doesn't delete the dial error after a peer is removed. I waited to reach the state where there were no more peers to send a light push, and found that every single dial error was the same:
```
[
    "The dial request has no valid addresses",
    "The dial request has no valid addresses",
    ...
    "The dial request has no valid addresses",
    "The dial request has no valid addresses"
]
```

This seems odd. I understand it should be the case for some of the peers, but for 133 of them to result in this error seems excessive.

**Comment by adklempner** [comment]
> I modified connection manager such that it doesn't delete the dial error after a peer is removed. I waited to reach the state where there were no more peers to send a light push, and found that every single dial error was the same:
> 
> ```
> [
>     "The dial request has no valid addresses",
>     "The dial request has no valid addresses",
>     ...
>     "The dial request has no valid addresses",
>     "The dial request has no valid addresses"
> ]
> ```
> 
> This seems odd. I understand it should be the case for some of the peers, but for 133 of them to result in this error seems excessive.

It seems that most peers are not running wss, in which case this is expected. I have a PR open for this but I want to do some additional testing before merging: https://github.com/waku-org/js-waku/pull/1983

Something else I discovered is that for some reason the peer store "loses" the metadata for a peer, specifically the shard info. Without this, the function called to  [getPeers](https://github.com/waku-org/js-waku/blob/86249dfe290d72c37a6848492eab8a0277a8f055/packages/core/src/lib/base_protocol.ts#L98) for light push filters out all of the peers because it thinks they don't support autosharding

**Comment by adklempner** [comment]
> Something else I discovered is that for some reason the peer store "loses" the metadata for a peer, specifically the shard info. Without this, the function called to [getPeers](https://github.com/waku-org/js-waku/blob/86249dfe290d72c37a6848492eab8a0277a8f055/packages/core/src/lib/base_protocol.ts#L98) for light push filters out all of the peers because it thinks they don't support autosharding

I believe I have found the culprit, but like the PR above it probably needs more testing https://github.com/waku-org/js-waku/pull/1984

**Comment by adklempner** [comment]
I believe I identified the prime suspect causing this issue (and dropping connections in general):
```
libp2p:connection:outbound:6qf7pg1714026544431:error error handling incoming stream id r7 +0ms Too many inbound protocol streams for protocol "/ipfs/ping/1.0.0" - limit 2 ERR_TOO_MANY_INBOUND_PROTOCOL_STREAMS CodeError: Too many inbound protocol streams for protocol "/ipfs/ping/1.0.0" - limit 2
    at http://localhost:3000/dist/bundle.js:55349:41
    
libp2p:connection:outbound:6qf7pg1714026544431 closing connection to /dns4/node-01.ac-cn-hongkong-c.waku.test.statusim.net/tcp/8000/wss/p2p/16Uiu2HAkzHaTP5JsUwfR9NR8Rj9HC24puS6ocaU8wze4QrXr9iXp +588ms
```

It seems what happens is:
1. peer tries to ping js-waku
2. there are already maximum amount of inbound streams opened from the peer to the node for the ping protocol
3. libp2p closes the entire connection?

**Comment by adklempner** [comment]
> I believe I identified the prime suspect causing this issue (and dropping connections in general):
> 
> ```
> libp2p:connection:outbound:6qf7pg1714026544431:error error handling incoming stream id r7 +0ms Too many inbound protocol streams for protocol "/ipfs/ping/1.0.0" - limit 2 ERR_TOO_MANY_INBOUND_PROTOCOL_STREAMS CodeError: Too many inbound protocol streams for protocol "/ipfs/ping/1.0.0" - limit 2
>     at http://localhost:3000/dist/bundle.js:55349:41
>     
> libp2p:connection:outbound:6qf7pg1714026544431 closing connection to /dns4/node-01.ac-cn-hongkong-c.waku.test.statusim.net/tcp/8000/wss/p2p/16Uiu2HAkzHaTP5JsUwfR9NR8Rj9HC24puS6ocaU8wze4QrXr9iXp +588ms
> ```
> 
> It seems what happens is:
> 
> 1. peer tries to ping js-waku
> 2. there are already maximum amount of inbound streams opened from the peer to the node for the ping protocol
> 3. libp2p closes the entire connection?

A mitigation for this that seems to work is increasing the maximum number of incoming connections for the ping protocol to 10 from the default of 2. I tried this with the light-js example and it's been running for 40 minutes without dropping below 9 peers, sending a light push message every 10 seconds. I'm not sure what are the performance implications of increasing this number but it seems preferable to the node losing peer connections and not recovering them.

**Comment by adklempner** [comment]
The most important fixes for this have been included in the latest release of js-waku. The remaining PR for filtering wss connections is not as relevant. @weboko can this be considered resolved?

**Comment by weboko** [comment]
Agree that this task is complete. If we observe any issues - let's action in the scope of some other bug / task. 
Thank you for documenting investigation well!
