### ISSUE TITLE
feat: filter.createSubscription accept ShardParams

### ISSUE THREAD

**Issue by vpavlin** [waku-org/js-waku#1967]
support request

## Problem

It seems like `filter.createSubscription` accepts either `pubsubTopic` or `SingleShardInfo` - which in turn consists of `ClusterId` and `shard`

Would it make more sense to accept `ShardingParams` to make it more flexible? 

Requiring `SingleShardInfo` forces me to get the shard from contentTopic before calling `createSubscription`, which seems unnecessary to be done by a user/dev. 

But I might be missing the reasoning behind this choice:)

**Comment by weboko** [comment]
I agree with @vpavlin and I think better way would be to simplify as much as possible but also allow to make fine tuning. 

For that I see we can do:
- make it accept `contentTopic` and map it to a shard;
- provide API for advanced users to set particular `shard` or other params;
