### ISSUE TITLE
chore: fail when both pubsubTopics and shardInfo are specified

### ISSUE THREAD

**Issue by vpavlin** [waku-org/js-waku#1980]
This is a **change request**

## Problem

When setting up light node, users can specify both `pubsubTopics` and `shardInfo` which seems to result in unwanted behaviour

## Proposed Solutions

Error out when both `pubsubTopics` and `shardInfo` are specified and suggest only one is provided

**Comment by weboko** [comment]
I jumped into conclusion that there is actually a problem - but after checking in one of my local examples or testing pipeline we have currently https://github.com/waku-org/js-waku/pull/1992 - there seems to be no error. 

Of course I agree this shouldn't happen - and some warning should be printed. 

@vpavlin please, share details what actually fails?
