### ISSUE TITLE
bug: message hash does not match the spec

### ISSUE THREAD

**Issue by vpavlin** [waku-org/js-waku#1982]
This is a **bug report**

## Problem

The message hash package (https://github.com/waku-org/js-waku/blob/master/packages/message-hash/src/index.ts) does not match the spec https://github.com/vacp2p/rfc-index/blob/main/waku/standards/core/14/message.md#deterministic-message-hashing - the `timestamp` is not included in the hash

## Proposed Solutions

include `timestamp`

**Comment by weboko** [comment]
Will be resolved in https://github.com/waku-org/js-waku/issues/1985
