### ISSUE TITLE
investigate suspended js-waku in suspended mode

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2000]
This is a **support request**

## Problem

Investigate how `js-waku` behaves in following scenarios: 
- tab with js-waku get's suspended or laptop goes to sleep;
- tab with lightPush or filter is kept for some time (10+ minutes);

Once particular problems are found - let's create them as bugs and fix accordingly. 

## Notes

Part of: https://github.com/waku-org/pm/issues/143

**Comment by adklempner** [comment]
Here's another scenario I tested which seems relevant:
1. Open light-js in two separate browsers
2. Subscribe to same topic on both
3. Send a message from browser A and verify it appears in browser B
4. In browser B set Network throttling to Offline
5. Send another message from browser A
6. Set network throttling off in browser B
7. Send another message from browser A

When I tried this, browser B does not receive messages from steps 5 and 7.

**Comment by adklempner** [comment]
Running light push and filter for 10+ minutes:
1. Open light-js in two separate browsers.
2. Subscribe to same topic on both
3. In browser A, send a message using light push every 10 seconds

Results:
- Browser A sent messages 1-30 correctly to 6 peers each
- Messages 31 and 32 reported remote peer fault for some peers
- Messages 33-114 sent to a single peer each (only managed to reconnect to a single peer after dropping connections)
- Browser A stopped seeing messages in its own filter subscription after message 31
- Browser B saw messages 1-30, missed 31, saw 32-63 and then missed messages after

Around message 115 is when my laptop suspended
After waking up:
- Browser A reconnected to 4 and then 6 peers and continued sending messages
- Browser B received messages 115-179 but stopped after
- Browser A received messages 115-146 but stopped after (although it continued to push them successfully)

**Comment by weboko** [comment]
Closing as investigation was done and we don't have explicit improvement to do for now.
