### ISSUE TITLE
bug: SANDBOX fleet is unstables

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2138]
This is a **bug report**

## Problem

Problems connecting to the fleets were observed. Narrowing down, it was found that there was a misconfiguration on the SANDBOX fleet: 
```
Reason: Payload identity key 08021221039377e879a30c23f9cc7bc6b99bbd0294f0257716899f76f72fd4c05cfbaed3e6 does not match expected remote identity key 0802122103af0f74b78d43480acace20b96684436258032631594097af90f30441ee189d63
```

Infra thus fixed the nodes and nodekeys, and a new ENRTree was generated.

## Proposed Solutions
Issue should be resolved now.
Update the new ENRTree if not

**Comment by weboko** [comment]
@danisharora099 to add description and track

**Comment by danisharora099** [comment]
Updated the issue. ENRTree to be updated

**Comment by weboko** [comment]
@danisharora099 to check if ENR need to be updated

**Comment by danisharora099** [comment]
The ENRTrees are updated, closing
