### ISSUE TITLE
feat: moving protocol peer management's source of truth into libp2p's metadata

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#2167]
This is an **improvement request**

## Problem
We currently rely on PeerManager that maintains a copy of peers being used for the protocol, and maintain the copy in-memory in an array. 

We might be able to improve this maintenance of the copy of peer list in an array, to the usage of metadata in Libp2p's PeerStore for the same.

## Proposed Solution
Experiment with moving the source of truth for which peers to use for protocols as part of the peer's metadata instead of an in-memory variable

## Notes
- ref: https://github.com/waku-org/js-waku/pull/2137#discussion_r1791512123

**Comment by danisharora099** [comment]
WIP efforts: https://github.com/waku-org/js-waku/pull/2172

**Comment by danisharora099** [comment]
some observations so far on this issue:

Pros:
- streamlined and global access to data on which peers are being used for which protocol

Cons:
- need of thread-blocking operations (`await`) when wanting to access peer object (`await this.peerStore.get()`)

**Comment by weboko** [comment]
let's research:
- impact of `await` on `libp2p.peerStore` in ms 
- usage of `Connection.metadata` field that is a plain dictionary 

relevant comment https://github.com/waku-org/js-waku/pull/2137/files#r1795552243

**Comment by weboko** [comment]
I think I found an approach to this problem and will tackle it in https://github.com/waku-org/js-waku/issues/2186
