### ISSUE TITLE
chore: downgrade nodejs to 18

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2171]
## Problem

Some of the consumers of the library are using [NodeJS mobile](https://nodejs-mobile.github.io/) which has support only for `nodejs@18`.

## Solution 

Downgrade NodeJS requirement in js-waku temporarily. 
We need to revert https://github.com/waku-org/js-waku/pull/2110

**Comment by weboko** [comment]
Important for the next release https://github.com/waku-org/js-waku/pull/2135

**Comment by danisharora099** [comment]
With experiments on PR #2173, downgrading to NodeJS18 will involve polyfilling some libraries with related dependencies that don't exist in Node18, which might also involve downgrading some js-waku dependencies that are not straightforward to polyfill.

The decision between polyfilling vs waiting for NodeJS mobile to [upgrade to Node22](https://github.com/nodejs-mobile/nodejs-mobile/pull/134) is a decision to make. Almost 40% of the upgrade on NodeJS mobile to Node22 has been achieved, and it might be better to hold off upgrading js-waku until the above PR is merged on NodeJS Mobile (ETA is end of October/2 weeks)

Assuming the library consumer in this context is @mattgle, what do you think?

cc @weboko

**Comment by weboko** [comment]
Closing as we agreed with Zy0n not to proceed with that and I believe @mattgle is on the same page.
