### ISSUE TITLE
bug: filter subscription is not working on cold start

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2190]
## Problem

When `js-waku` tab is open for first time sometimes Filter doesn't work

## Solution

Investigate and fix

**Comment by vpavlin** [comment]
I think I've seen this too, but it started working after a while (even without reload, I believe, but I will check again)

**Comment by weboko** [comment]
It seems that `peer:identify` kicks in later so that when `js-waku` has already a connection - it usually not negotiated fully so `waitForPeers` starts waiting for new `peer:identify` events 

![Image](https://github.com/user-attachments/assets/cae71d7a-2e8e-48eb-b5d0-5d685f9e982b)

If it is the case that means that:
- if `waitForPeers` is used - it will block execution unless there are more than one node present;
- if `waitForPeers` is not used but subscription is getting initiated right after dial / bootstrap of the node - it might not have peers / protocols populated at that point in time;
