### ISSUE TITLE
Code example in Metamask snap

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#277]
To demonstrate wallet-dapp integration with Waku, let's create a metamask extension using their snap framework: https://medium.com/metamask/introducing-the-next-evolution-of-the-web3-wallet-4abdf801a4ee

The example could be an other eth-pm or maybe something more M2M like such as a notification from a contract owner (DAO) to token holder.

**Comment by reisepass** [comment]
This is marked as closed "Done" just wondering if you could point to where the metamask snap code is ?

**Comment by fryorcraken** [comment]
@reisepass this was closed as "not done" :)
