### ISSUE TITLE
Implement Waku Filter Protocol

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#290]
## Problem

The Waku Filter protocol allow light clients to save bandwidth but only receiving messages of the target content topic, and not relaying/forwarding messages. See https://rfc.vac.dev/spec/12/ for details.

## DoD

- [ ] Filter protocol implemented with tests using nim-waku
- [ ] Doc published with new example that demonstrate filter used with light push

**Comment by D4nte** [comment]
Effort already made to make it work with go-waku.
Need to test/merge:
- https://github.com/status-im/go-waku/pull/241
- https://github.com/status-im/js-waku/pull/711

**Comment by D4nte** [comment]
Initial implementation done: https://github.com/status-im/js-waku/pull/762 but only works in NodeJS with a listening node.

Blocked by:
- https://github.com/status-im/go-waku/issues/245
- https://github.com/status-im/nwaku/issues/948

**Comment by danisharora099** [comment]
> Initial implementation done: #762 but only works in NodeJS with a listening node.
> 
> Blocked by:
> 
>     * [Filter does not push messages to js-waku in the Browser go-waku#245](https://github.com/waku-org/go-waku/issues/245)
> 
>     * [Waku Filter In The Browser nwaku#948](https://github.com/waku-org/nwaku/issues/948)

I see both the PRs have been merged. Is the status updated?

**Comment by fryorcraken** [comment]
Yep done :)
