### ISSUE TITLE
Write RFC for relay ping

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#562]
# Problem

Keep alive implemented in js-waku Waku Relay: See https://github.com/status-im/js-waku/pull/243

It is not documented

# DoD

- [ ] Check it still needed (see #751)
- [ ] Open issue in vacp2p/rfc
- [ ] Write RFC

**Comment by fryorcraken** [comment]
It does not make sense to keep flooding the network.
Superseded by https://github.com/waku-org/js-waku/issues/1349
