### ISSUE TITLE
Provide sync constructor and async `start` methods for `Waku`

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#677]
This is a **feature request**

## Problem

The only way to create a `Waku` object is to use the async method `Waku.create`.

This can be an issue in situation where a consumer wishes to instantiate `Waku` object in a sync context (e.g. class constructor) and proceed with the async operation (.e.g starting the Waku node) in a different context.

## Proposed Solutions

- Make the `Waku.constructor` public, move all non-async `create` operations to it
- Add a `Waku.start` method that proceed with async operations and starting the Waku node
- Keep the `Waku.create` method as a way to create and start a Waku node, make it use the constructor and `start` method above so that `Waku.create` and `new Waku(), waku.start()` produce the same result.

**Comment by fryorcraken** [comment]
API has totally changed since this issue. We now use `createLightNode` and a lot of logic has moved to the `constructor` already.
