### ISSUE TITLE
Make `WakuRelay` API closer to `EventEmitter`

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#678]
This is a **feature request**

## Problem

The `WakuRelay` API implements the observer design pattern.
It is reminiscent of NodeJS's `EventEmitter`, which is a popular interface in the JS that also implement the observer design pattern:

| `WakuRelay` | `EventEmitter` |
| --- | --- |
| `send` | `emit` |
| `addObserver` | `on` |
| `deleteObserver` | `removeListener` |

However, `WakuRelay`'s API is very limited in comparison to `EventEmitter`.

See https://nodejs.org/api/events.html for details.

When implementing a socket-like usage of js-waku for WebRTC, I have found the lack of `once` and  `removeAllListeners` limiting.

Note: the API does not use the same function names because `WakuRelay` extends `EventEmitter` by transition.

## Proposed Solutions

Implement the following methods on `WakuRelay`:

| `WakuRelay` | `EventEmitter` equivalent |
| --- | --- |
| `addOnceObserver` | `once` |
| `removeAllObservers` | `removeAllListeners` |

Feel free to implement all methods equivalent but having check I am uncertain there other methods worth it apart from prepend and count.

**Comment by fryorcraken** [comment]
`once` does not really work because one cannot trust that the next message arriving on a given content topic is valid and not spam/garbage.

The work done in https://github.com/waku-org/js-noise/issues/14 enables us to already improve the API for a concrete use case.

Iceboxing for now until we have a concrete need or request of API from developers.

**Comment by weboko** [comment]
I think current issue lost it's actuality to https://github.com/waku-org/js-waku/issues/1635 so it should be safe to close this one

**Comment by fryorcraken** [comment]
#1635 is more around wrappers.


However, happy to close this and just track work based on recent/popular developer feedback.
