### ISSUE TITLE
Review React Guide

### ISSUE THREAD

**Issue by D4nte** [waku-org/js-waku#739]
When following https://docs.wakuconnect.dev/docs/guides/07_reactjs_relay/ with `js-waku@0.22.0` I noticed that I only needed to install `assert` for the example to work:
- `cra-webpack-rewired` and overriding the webpack config are not needed
- No other polyfills are needed

The polyfills might only be needed when using specific modules (ie, `Buffer` might be used only for the cryptography).

We should better understand and document the polyfill needs, especially if it makes the library easier to use.

**Comment by D4nte** [comment]
Note `assert` was removed: https://github.com/status-im/js-waku/pull/740

**Comment by D4nte** [comment]
To be done when documenting `@waku/core` as part of #802.

**Comment by taylorferran** [comment]
Was this completed during #802 @fryorcraken ? And can it be closed

Just came across this when looking for a good first issue

**Comment by fryorcraken** [comment]
Closing this as **all** guides need to be reviewed.
