### ISSUE TITLE
improve fallback behavior for queryHistory

### ISSUE THREAD

**Issue by dmh1974** [waku-org/js-waku#750]
when no message history is present the library will log to console that no history is present but i cant catch this in anyway

**Comment by D4nte** [comment]
> when no message history is present the library will log to console that no history is present but i cant catch this in anyway

What behaviour would you like to see? `queryHistory` will return an empty array which should give you a hint that no message was returned.

No message returned is a functionally valid scenario so I am not sure it would make sense to throw an error.

**Comment by dmh1974** [comment]
can you demonstrate in what syntax an empty array is returned? from what i see it relies on a callback and if there are no messages it just never calls back and just logs to console no messages present

**Comment by D4nte** [comment]
> can you demonstrate in what syntax an empty array is returned? from what i see it relies on a callback and if there are no messages it just never calls back and just logs to console no messages present

https://github.com/status-im/js-waku/blob/2011c76b30da203816da1780a7359c7b812af306/src/lib/waku_store/index.node.spec.ts#L55

But let's say you only want to use the callback: what kind of behaviour or API would you expect?

**Comment by dmh1974** [comment]
thanks, i swear i tried that and couldn't get the call to return anything to a var.. ill try again at some point to verify that part

for your second q, i personally would find it handy if when reaching the end of range it returned a false or empty array for the final callback

**Comment by D4nte** [comment]
> thanks, i swear i tried that and couldn't get the call to return anything to a var.. ill try again at some point to verify that part
> 
> for your second q, i personally would find it handy if when reaching the end of range it returned a false or empty array for the final callback

A `false` seems hack-ish. An empty array would be ok-ish. I think the most idiomatic way would be an async iterable because it would communicate whether or not it's the last value. WDYT?

**Comment by dmh1974** [comment]
agreed, i tried to get an async await response from the call but couldn't seem to do so. ive worked with other libraries that return an empty (sub)array on a callback as well, which is also helpful in some scenarios. both would be most superb, imho

**Comment by D4nte** [comment]
Proposed change:

1. Create new generator function/API that does the store queries (async iterator)
2. Use (1) to provide new function that takes a `callback` parameter, `callback` is called with empy array after last page (or only on empty array if there no results.
3. Use (1) to provide function that returns all results in one promise
4. deprecate current `queryHistory`.
