### ISSUE TITLE
Additional tabs can no longer connect after 10 open tabs in browser

### ISSUE THREAD

**Issue by dmh1974** [waku-org/js-waku#752]
currently using testnet

maybe nwaku related

you can reproduce the results here

https://gateway.pinata.cloud/ipfs/QmUS84DM9wLhmXnVf1EB41uoGc4HobTPc9W2CMAUWQRMFs?topic=BTCUSDT

duplicate tabs, 11th+ tab and so on will not connect

**Comment by fryorcraken** [comment]
This is a bug report. Let's try to reproduce ourselves first before icing/discarding.

**Comment by fryorcraken** [comment]
- [ ] Try an example that uses lightpush/filter, open 11+ tabs, check if messages are still received/sent
- [ ] same with a relay example, open 11+ tabs, check if messages are still received/sent

**Comment by weboko** [comment]
Issue is not observed on 11+ tabs. I think it's safe to close though idea with a web worker is useful and I propose to pursue it in this issue https://github.com/waku-org/js-waku-examples/issues/211


I had strange behaviour at https://examples.waku.org/relay-js/ when connection to the node fails. Is it happens to you too @danisharora099 / @fryorcraken ?

**Comment by fryorcraken** [comment]
> I had strange behaviour at [examples.waku.org/relay-js](https://examples.waku.org/relay-js/) when connection to the node fails. Is it happens to you too @danisharora099 / @fryorcraken ?

Yes, https://github.com/waku-org/pm/issues/23
