### ISSUE TITLE
ci: automated release process

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#890]
This is a **change request**

## Problem

The release process is manual, hence it is difficult to _release early, release often_.

This repo will become a multi-repo soon #802 and hence we need to make the releasing of the various packages easier.

Ideally, one button click should be enough for a maintainer to release and publish.

Also, automation of the changelog should be considered, using [Conventional Commits](conventionalcommits.org/)

## Acceptance Criteria

- [ ] Changelog is maintained from commits using conventional commits
- [ ] New PR automatically opens when changes are merged, version (patch, minor) is deduced from conventional commits (breaking change or not)
- [ ] Maintainer can merge PR for release to happen
- [ ] Minimum manual action should still be needed from the maintainer
- [ ] Automated release and publication of all merged PR under a release candidate version (ie `0.23.0-<short commit hash>`) with a `next` tag on npmjs.com https://github.com/status-im/js-waku/pull/896

## Notes

Check out the following repos for ideas:
- https;//github.com/libp2p/js-libp2p
- https://github.com/chainSafe/js-libp2p-gossipsub

**Comment by weboko** [comment]
How it will work with `release-please`:
- PR will be automatically created and updated based on master;
- major increment will be made only if breaking change is introduced as per conventional commit spec;
- the only action is for maintainer to complete a PR;
