### ISSUE TITLE
Peer not found despite using waitForRemotePeer

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#913]
When using `waitForRemotePeer` with `store`, a strange behaviour happens with the underlying libp2p `peerStore`:

1. `waitForRemotePeer` resolves, I can confirm that the `peerStore` contains a peer with `store` protocol.
2. Use `WakuStore.queryHistory`: exception is thrown because it could not find a peer in the peer store: ` Failed to retrieve messages Failed to find known peer that registers waku store protocol`
3. Then the peer re-appears in the peer store.

When looking at the logs, I can see a lot of events on the `peerStore`. the addition and removal and re-addition of the peer is unexpected.

**Comment by danisharora099** [comment]
How can this be reproduced? 
The store tests, that use `waitForRemotePeer` and queries, pass correctly.

**Comment by fryorcraken** [comment]
try with `store-js` example see if it happens for you.

**Comment by danisharora099** [comment]
Unable to reproduce this with`queryOrderedCallback` - retrieving all messages successfully.
Does the `store-js` example not work for you completely?

@fryorcraken

**Comment by weboko** [comment]
I am no able to repro this issue in the `store-js` example.

**Comment by fryorcraken** [comment]
Ok, let's assume local fluke until further reporting
