### ISSUE TITLE
Auto-extract modules path from package.json file

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#933]
## Problem

The exports map is replicated in several places:
- https://github.com/status-im/js-waku/blob/d9d237b7ac2db8031522d0b3b554d5ebd6bb2651/package.json#L7
- https://github.com/status-im/js-waku/blob/d9d237b7ac2db8031522d0b3b554d5ebd6bb2651/rollup.config.js#L6
- https://github.com/status-im/js-waku/blob/d9d237b7ac2db8031522d0b3b554d5ebd6bb2651/typedoc.json#L2

Which means it is easy to forget adding a new module to one of these locations

## Proposed Solutions

Make `package.json` the source of truth by importing its exports map in the rollup and typedoc configs.

## Notes

`typedoc.json` can be convert to a (C)JS file.

**Comment by fryorcraken** [comment]
This is only a dupe between `package.json` and `rollup.js`. Hopefully we can extract the info from the former into the latter.

**Comment by weboko** [comment]
@fryorcraken , do I understand it correctly that those imports in the `package.json` are necessary to build exports of `js-waku` npm package properly. In case `@waku/core` or some other package is consumed - those `exports` are not needed?

**Comment by fryorcraken** [comment]
> @fryorcraken , do I understand it correctly that those imports in the `package.json` are necessary to build exports of `js-waku` npm package properly. In case `@waku/core` or some other package is consumed - those `exports` are not needed?

Sorry I don't understand the question...

IMO, one needs to specify in rolliup config the entries of the `package.json`'s `exports' map to ensure rollup bundle them,
Otherwise, rollup just bundles the `main` entry `index.js` and those other paths are not available in the bundle.

This is an odd behaviour I agree. Maybe there is an option in rollup to read the `exports` map of the `package.json`?

If not, then one can simply import the `package.json` content and use it to create the rollup config. Similarly to what is done in the typedoc config for the `workspaces` values: https://github.com/waku-org/js-waku/blob/74353695fecbeb5ced383e9199c9ca45dc3d6bf1/typedoc.cjs
