### ISSUE TITLE
Store Improvements

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#937]
## Problem

- `WakuStore.queryHistory` is one big function, a functional split would be good
- Store operations involve several async operations (network, subtle crypto API), not sure the succession of the operations are optimized. e.g. an `await Promise.all` is currently used inside `queryHistory`.
- Presently, new stream is created for each page request, yet page requests have to be done sequentially so same stream could be used (if not closed) (because of the cursor)
- API feedback has been received: https://github.com/status-im/js-waku/issues/750

## Proposed Solutions

Split the function in smaller sections:

- peer selection logic
- connection selection logic
- processing of each page

Also review if the same stream can be re-used for each request.
Cater for a new stream being needed if the previous stream closed.

Review if we can parallelize the decryption operation.
See if benchmark tests can be added

Probably use an async iterator for the pagination.

There could be a couple of public API: one async iterator (may not be as performant, benchmark tests would help) and one that returns an array of promises (instead of a promise of an array) so that decryption and any async callback are done in "parallel".

**Comment by fryorcraken** [comment]
Considering this one done as a new API has been provided: https://github.com/waku-org/js-waku/blob/6e4ff0f2b8321a36e625e9c42b1e36351260f31b/packages/core/src/lib/waku_store/index.ts#L131

**Comment by danisharora099** [comment]
> Presently, new stream is created for each page request, yet page requests have to be done sequentially so same stream could be used (if not closed) (because of the cursor)

Not sure about the quantitative performance difference this can provide, but this sounds like a great idea. Are we following up on/tracking this?

**Comment by fryorcraken** [comment]
> > Presently, new stream is created for each page request, yet page requests have to be done sequentially so same stream could be used (if not closed) (because of the cursor)
> 
> Not sure about the quantitative performance difference this can provide, but this sounds like a great idea. Are we following up on/tracking this?

Good catch https://github.com/waku-org/js-waku/issues/1130
