### ISSUE TITLE
Publish doc to js.waku.org

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#943]
We are retiring the "Waku Connect" branding and websites in favour of Waku and waku.org

The documentation previously [published](https://github.com/waku-org/js-waku/blob/7cc0289132c8e4d1070e777821fdf63aabbd74d2/ci/Jenkinsfile.gh-pages#L29) at https://js-waku.wakuconnect.dev/ should now be published to js.waku.org.

@jakubgs Are you happy to handle this? Thanks!

FYI, I removed the Jenkins conf by mistake recently, I re-added it but it still did not trigger any build: https://ci.infra.status.im/job/website/job/js-waku.wakuconnect.dev/

Not sure if I broke something there.

**Comment by jakubgs** [comment]
The webhook URL was incorrect. I fixed it.

**Comment by jakubgs** [comment]
Infra changes:

- https://github.com/status-im/infra-misc/commit/3d73fcd5 - move js-waku site to js.waku.org

And PR:

* https://github.com/waku-org/js-waku/pull/945

Moved builds to: https://ci.infra.status.im/job/website/job/js.waku.org/
