### ISSUE TITLE
Add Ephemeral flag to WakuMessage

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#949]
## Problem

New Waku Message field to alleviate store resources: https://github.com/vacp2p/rfc/pull/532

## Acceptance Criteria

- [x] Library consumer can set the field (unset by default)
- [ ] Relay Ping messages have ephemeral field set
- [ ] Eth-pm has the ephemeral field set

## Notes

Blocked on #935.

**Comment by fryorcraken** [comment]
Might be impacted by https://github.com/waku-org/js-waku/issues/979

**Comment by danisharora099** [comment]
>     * [ ]  Relay Ping messages have ephemeral field set
>     * [ ]  Eth-pm has the ephemeral field set

what is the expected/intended behavior of the messages after the changes?

**Comment by fryorcraken** [comment]
>  Relay Ping messages have ephemeral field set

The relay ping messages that are sent here https://github.com/waku-org/js-waku/blob/0b083201c6f585ad1b3267c1571df5f1b81a1355/packages/core/src/lib/waku.ts#L241 have ephemeral true

> Eth-pm has the ephemeral field set

All messages sent by the eth-pm example have ephemeral true (this example does not use store)

**Comment by danisharora099** [comment]
> > Relay Ping messages have ephemeral field set
> 
> The relay ping messages that are sent here
> 
> https://github.com/waku-org/js-waku/blob/0b083201c6f585ad1b3267c1571df5f1b81a1355/packages/core/src/lib/waku.ts#L241
> have ephemeral true
> 
> > Eth-pm has the ephemeral field set
> 
> All messages sent by the eth-pm example have ephemeral true (this example does not use store)

Correct. Do we want to introduce the usage of querying past messages from the recipient using store protocol?

**Comment by danisharora099** [comment]
The pending TODOs have been addressed and this PR should close once related PRs are merged.
