### ISSUE TITLE
js.waku.org does not get published

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#966]
This is a **bug report/**

## Problem

The Jenkins pipeline has not been triggered since 11 September despite many PRs merged on master: https://ci.infra.status.im/job/website/job/js.waku.org/

**Comment by fryorcraken** [comment]
@jakubgs can you please assist?

**Comment by jakubgs** [comment]
I can see the webhooks are working:

![image](https://user-images.githubusercontent.com/2212681/191510487-7f6f19a8-3ea1-4c9b-89d9-dcd5c98a6d52.png)

**Comment by jakubgs** [comment]
Ohhh, the branch wasn't updated after domain name fix:

![image](https://user-images.githubusercontent.com/2212681/191510703-893b5708-5d7f-4b49-baad-ab914816fff4.png)

Fixed.
