### ISSUE TITLE
`queryOrderedCallback` cannot be aborted

### ISSUE THREAD

**Issue by filoozom** [waku-org/js-waku#978]
This is a **bug report**

## Problem

In https://github.com/waku-org/js-waku/blob/29436eaf/src/lib/waku_store/index.ts#L108-L137, `abort` can never be set to `true`, meaning that the function cannot be aborted by returning `true` from the callback.

## Proposed Solutions

I guess something like:
```ts
await Promise.all(
  messages.map((msg) => {
    if (!abort) {
      if (msg) return callback(msg);
    }
  })
).then(results => results.some(abort => abort))
```
but I haven't really looked into it enough.

## Notes

- `js-waku`: `0.29.0`
- tested on our own `nim-waku` nodes (`v0.12.0`)

**Comment by fryorcraken** [comment]
Yep, also confirmed when using store-js
